### ISSUE TITLE
Package repository not available error message / traceback

### ISSUE THREAD

**Issue by iankko** [cekit/cekit#245]
Running latest cekit installed per [instructions from the docs](https://github.com/cekit/cekit/blob/develop/README.rst#installation), trying to build RH-SSO for OpenShift image:

```
mkdir -p /tmp/github && cd /tmp/github
git clone https://github.com/jboss-container-images/redhat-sso-7-openshift-image.git
$ cd redhat-sso-7-openshift-image/
```
returns:

```
$ cekit build --build-engine=docker
2018-06-07 16:38:53,734 cekit        INFO     Generating files for docker engine.
2018-06-07 16:38:53,776 cekit        INFO     Initializing image descriptor...
2018-06-07 16:38:55,664 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 16:38:55,664 cekit        ERROR    Package repository 'jboss-os' used in descriptor is not available in Concreate configuration file. Available repositories: dict_keys([])
```

Verbose output of the same:

```
$ cekit build -v --build-engine=docker
2018-06-07 16:39:31,656 cekit        DEBUG    Running version 2.0.0rc6
2018-06-07 16:39:31,657 cekit        DEBUG    Removing dirty directory: 'target/repo'
2018-06-07 16:39:31,674 cekit        INFO     Generating files for docker engine.
2018-06-07 16:39:31,674 cekit        DEBUG    Loading descriptor from path 'image.yaml'.
2018-06-07 16:39:31,717 cekit        INFO     Initializing image descriptor...
2018-06-07 16:39:31,717 cekit        DEBUG    Retrieving module repositories for 'redhat-sso-7/sso72-openshift'
2018-06-07 16:39:31,717 cekit        DEBUG    Fetching resource 'cct_module'
2018-06-07 16:39:31,717 cekit        DEBUG    Running 'git clone --depth 1 https://github.com/jboss-openshift/cct_module.git target/repo/cct_module.git-master -b master'
2018-06-07 16:39:33,600 cekit        DEBUG    Artifact 'cct_module' lacks any checksum definition, it will be replaced
2018-06-07 16:39:33,601 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/s2i-common/module.yaml'.
2018-06-07 16:39:33,604 cekit        DEBUG    Retrieving module repositories for 's2i-common'
2018-06-07 16:39:33,604 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,605 cekit        DEBUG    Adding module 's2i-common', path: 'target/repo/cct_module.git-master/s2i-common'
2018-06-07 16:39:33,605 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/sso71/module.yaml'.
2018-06-07 16:39:33,609 cekit        DEBUG    Retrieving module repositories for 'product.sso71'
2018-06-07 16:39:33,609 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,609 cekit        DEBUG    Adding module 'product.sso71', path: 'target/repo/cct_module.git-master/products/sso71'
2018-06-07 16:39:33,610 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/kieserver6x/module.yaml'.
2018-06-07 16:39:33,617 cekit        DEBUG    Retrieving module repositories for 'product.kieserver6x'
2018-06-07 16:39:33,617 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,617 cekit        DEBUG    Adding module 'product.kieserver6x', path: 'target/repo/cct_module.git-master/products/kieserver6x'
2018-06-07 16:39:33,617 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/eap71/module.yaml'.
2018-06-07 16:39:33,623 cekit        DEBUG    Retrieving module repositories for 'product.eap71'
2018-06-07 16:39:33,624 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,624 cekit        DEBUG    Adding module 'product.eap71', path: 'target/repo/cct_module.git-master/products/eap71'
2018-06-07 16:39:33,624 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/eap70/module.yaml'.
2018-06-07 16:39:33,631 cekit        DEBUG    Retrieving module repositories for 'product.eap70'
2018-06-07 16:39:33,632 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,632 cekit        DEBUG    Adding module 'product.eap70', path: 'target/repo/cct_module.git-master/products/eap70'
2018-06-07 16:39:33,632 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/eap64/module.yaml'.
2018-06-07 16:39:33,638 cekit        DEBUG    Retrieving module repositories for 'product.eap64'
2018-06-07 16:39:33,638 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,639 cekit        DEBUG    Adding module 'product.eap64', path: 'target/repo/cct_module.git-master/products/eap64'
2018-06-07 16:39:33,639 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/datavirt6x/module.yaml'.
2018-06-07 16:39:33,644 cekit        DEBUG    Retrieving module repositories for 'product.datavirt6x'
2018-06-07 16:39:33,645 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,645 cekit        DEBUG    Adding module 'product.datavirt6x', path: 'target/repo/cct_module.git-master/products/datavirt6x'
2018-06-07 16:39:33,645 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/datagrid71/module.yaml'.
2018-06-07 16:39:33,649 cekit        DEBUG    Retrieving module repositories for 'product.datagrid71'
2018-06-07 16:39:33,649 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,650 cekit        DEBUG    Adding module 'product.datagrid71', path: 'target/repo/cct_module.git-master/products/datagrid71'
2018-06-07 16:39:33,650 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/datagrid65/module.yaml'.
2018-06-07 16:39:33,654 cekit        DEBUG    Retrieving module repositories for 'product.datagrid65'
2018-06-07 16:39:33,655 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,655 cekit        DEBUG    Adding module 'product.datagrid65', path: 'target/repo/cct_module.git-master/products/datagrid65'
2018-06-07 16:39:33,655 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/common/eap7x/module.yaml'.
2018-06-07 16:39:33,667 cekit        DEBUG    Retrieving module repositories for 'product.common.eap7x'
2018-06-07 16:39:33,667 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,667 cekit        DEBUG    Adding module 'product.common.eap7x', path: 'target/repo/cct_module.git-master/products/common/eap7x'
2018-06-07 16:39:33,667 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/products/common/eap6x/module.yaml'.
2018-06-07 16:39:33,684 cekit        DEBUG    Retrieving module repositories for 'product.common.eap6x'
2018-06-07 16:39:33,684 cekit        DEBUG    No module repositories specified in descriptor
2018-06-07 16:39:33,684 cekit        DEBUG    Adding module 'product.common.eap6x', path: 'target/repo/cct_module.git-master/products/common/eap6x'
2018-06-07 16:39:33,685 cekit        DEBUG    Loading descriptor from path 'target/repo/cct_module.git-master/os-sso72/module.yaml'.
2018-06-07 16:39:33,691 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 16:39:33,692 cekit        ERROR    Package repository 'jboss-os' used in descriptor is not available in Concreate configuration file. Available repositories: dict_keys([])
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cekit/cli.py", line 197, in run
    discover_modules(os.path.join(self.args.target, 'repo'))
  File "/usr/lib/python3.6/site-packages/cekit/module.py", line 92, in discover_modules
    'module.yaml'))))
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/module.py", line 31, in __init__
    self._prepare()
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/image.py", line 87, in _prepare
    self._descriptor['packages'] = Packages(self._descriptor['packages'])
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/packages.py", line 46, in __init__
    self._prepare()
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/packages.py", line 50, in _prepare
    for x in self._descriptor.get('repositories', [])]
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/packages.py", line 50, in <listcomp>
    for x in self._descriptor.get('repositories', [])]
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/packages.py", line 64, in __init__
    descriptor = self._create_repo_object(descriptor)
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/packages.py", line 84, in _create_repo_object
    descriptor['url']['repository'] = self._get_repo_url(descriptor)
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/packages.py", line 102, in _get_repo_url
    % (descriptor['name'], configured_repository_names))
cekit.errors.CekitError: Package repository 'jboss-os' used in descriptor is not available in Concreate configuration file. Available repositories: dict_keys([])
```

Checked with @goldmann and per his suggestion, to fix this it requires to port the repo files to new schema definition, as described in [Upgrading from Concreate section](http://docs.cekit.io/en/develop/upgrade.html#upgrading-from-concreate). But besides that, the "dict_keys([])" shouldn't be reported as an available repository as above.

**Comment by iankko** [comment]
@dbecvarik Could you have a look?

Thanks, Jan

**Comment by iankko** [comment]
JFTR, once the former dotfile config was migrated to cekit config via steps in [Dotfile migration](http://docs.cekit.io/en/develop/upgrade.html#dotfile-migration), the error turned into warning:
```
$ cekit build --build-engine=docker
2018-06-07 17:03:39,462 cekit        INFO     Generating files for docker engine.
2018-06-07 17:03:39,504 cekit        INFO     Initializing image descriptor...
2018-06-07 17:03:41,425 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 17:03:41,753 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 17:03:41,785 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 17:03:41,801 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 17:03:41,801 cekit        WARNING  The way of defining repository 'jboss-rhscl' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
2018-06-07 17:03:41,915 cekit        WARNING  The way of defining repository 'jboss-rhscl' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
...
```
And the image build continues / finishes.
