### ISSUE TITLE
Issue when trying to build eap71-openshift image

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#251]
2018-06-08 17:32:18,235 cekit        DEBUG    Merging 'os-java-run' module into 'dynamic-resources'.
Traceback (most recent call last):
  File "/usr/bin/cekit", line 11, in <module>
    load_entry_point('cekit==2.0.0rc5', 'console_scripts', 'cekit')()
  File "/usr/lib/python3.6/site-packages/cekit/cli.py", line 261, in run
    Cekit().parse().run()
  File "/usr/lib/python3.6/site-packages/cekit/cli.py", line 201, in run
    generator.prepare_modules()
  File "/usr/lib/python3.6/site-packages/cekit/generator/base.py", line 102, in prepare_modules
    self.prepare_modules(req_module)
  File "/usr/lib/python3.6/site-packages/cekit/generator/base.py", line 104, in prepare_modules
    descriptor.merge(req_module)
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/base.py", line 72, in merge
    _merge_descriptors(self, descriptor)
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/base.py", line 142, in _merge_descriptors
    desc1[k2].merge(v2)
  File "/usr/lib/python3.6/site-packages/cekit/descriptor/execute.py", line 70, in merge
    for executes in reversed(descriptor):
TypeError: 'ExecuteContainer' object is not reversible

**Comment by spolti** [comment]
in the 2.0.0rc5 this line https://github.com/cekit/cekit/blob/develop/cekit/descriptor/execute.py#L70 were 'for executes in reversed(descriptor):'

but on master, it is fixed already.
