### ISSUE TITLE
AttributeError: 'Module' object has no attribute 'version' with certain module dependency graph

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#322]
Given this stripped-down example of inter-dependent modules, that looks like this:

![graph-e6af185b1aaa16e8c7af0bb8213b0c32f0dc389d](https://user-images.githubusercontent.com/63694/47289863-9d253d00-d5f4-11e8-9ecd-52bb87b44520.png)

The version dependency from image.yaml is crucial to reproduce the bug

image.yaml:
```
schema_version: 1

from: "rhel7"
name: "testimage"
version: "1.0"

modules:
  repositories:
  - path: modules
  install:
  - name: a
    version: "foo"
  - name: b
```
modules/a/module.yaml:
```
schema_version: 1
name: a
version: "foo"
```
modules/b/module.yaml:
```
schema_version: 1
name: b
version: '1.0'

modules:
  install:
  - name: c
```
modules/c/module.yaml:
```
schema_version: 1
name: c
version: '1.0'

modules:
  install:
  - name: d
```
modules/d/module.yaml:
```
schema_version: 1
name: d
version: '1.0'

modules:
  install:
  - name: a
```

The result is as follows

```
$ cekit -v generate
2018-10-19 08:35:32,942 cekit        DEBUG    Running version 2.1.4
2018-10-19 08:35:32,943 cekit        INFO     Generating files for docker engine.
2018-10-19 08:35:32,944 cekit        DEBUG    Loading descriptor from path 'image.yaml'.
2018-10-19 08:35:32,974 cekit        INFO     Initializing image descriptor...
2018-10-19 08:35:32,974 cekit        DEBUG    Retrieving module repositories for 'testimage'
2018-10-19 08:35:32,975 cekit        DEBUG    Preparing resource 'modules'
2018-10-19 08:35:32,975 cekit        DEBUG    Copying repository from '/home/ce/mod-bug/strip/redhat-openjdk-18-openshift-image/modules' to 'target/repo/modules'.
2018-10-19 08:35:32,982 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/a/module.yaml'.
2018-10-19 08:35:32,985 cekit        DEBUG    Retrieving module repositories for 'a'
2018-10-19 08:35:32,985 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:32,985 cekit        DEBUG    Adding module 'a', path: 'target/repo/modules/a'
2018-10-19 08:35:32,985 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/b/module.yaml'.
2018-10-19 08:35:32,989 cekit        DEBUG    Retrieving module repositories for 'b'
2018-10-19 08:35:32,989 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:32,989 cekit        DEBUG    Adding module 'b', path: 'target/repo/modules/b'
2018-10-19 08:35:32,989 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/c/module.yaml'.
2018-10-19 08:35:32,993 cekit        DEBUG    Retrieving module repositories for 'c'
2018-10-19 08:35:32,993 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:32,993 cekit        DEBUG    Adding module 'c', path: 'target/repo/modules/c'
2018-10-19 08:35:32,993 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/d/module.yaml'.
2018-10-19 08:35:32,996 cekit        DEBUG    Retrieving module repositories for 'd'
2018-10-19 08:35:32,996 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:32,997 cekit        DEBUG    Adding module 'd', path: 'target/repo/modules/d'
2018-10-19 08:35:32,997 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/a/module.yaml'.
2018-10-19 08:35:32,999 cekit        DEBUG    Retrieving module repositories for 'a'
2018-10-19 08:35:32,999 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:32,999 cekit        DEBUG    Adding module 'a', path: 'target/repo/modules/a'
2018-10-19 08:35:32,999 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/b/module.yaml'.
2018-10-19 08:35:33,004 cekit        DEBUG    Retrieving module repositories for 'b'
2018-10-19 08:35:33,004 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:33,004 cekit        DEBUG    Adding module 'b', path: 'target/repo/modules/b'
2018-10-19 08:35:33,004 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/c/module.yaml'.
2018-10-19 08:35:33,007 cekit        DEBUG    Retrieving module repositories for 'c'
2018-10-19 08:35:33,007 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:33,007 cekit        DEBUG    Adding module 'c', path: 'target/repo/modules/c'
2018-10-19 08:35:33,007 cekit        DEBUG    Loading descriptor from path 'target/repo/modules/d/module.yaml'.
2018-10-19 08:35:33,011 cekit        DEBUG    Retrieving module repositories for 'd'
2018-10-19 08:35:33,011 cekit        DEBUG    No module repositories specified in descriptor
2018-10-19 08:35:33,011 cekit        DEBUG    Adding module 'd', path: 'target/repo/modules/d'
2018-10-19 08:35:33,012 cekit        DEBUG    Preparing module 'b' requested by 'testimage'.
2018-10-19 08:35:33,012 cekit        DEBUG    Copying module 'b' to: 'target/image/modules/b'
2018-10-19 08:35:33,012 cekit        DEBUG    Preparing module 'c' requested by 'b'.
2018-10-19 08:35:33,013 cekit        DEBUG    Copying module 'c' to: 'target/image/modules/c'
2018-10-19 08:35:33,013 cekit        DEBUG    Preparing module 'd' requested by 'c'.
2018-10-19 08:35:33,013 cekit        DEBUG    Copying module 'd' to: 'target/image/modules/d'
2018-10-19 08:35:33,014 cekit        DEBUG    Preparing module 'a' requested by 'd'.
2018-10-19 08:35:33,014 cekit        DEBUG    Copying module 'a' to: 'target/image/modules/a'
2018-10-19 08:35:33,017 cekit        DEBUG    Merging 'a' module into 'd'.
2018-10-19 08:35:33,017 cekit        DEBUG    Merging 'd' module into 'c'.
2018-10-19 08:35:33,017 cekit        DEBUG    Merging 'c' module into 'b'.
2018-10-19 08:35:33,018 cekit        DEBUG    Merging 'b' module into 'testimage'.
2018-10-19 08:35:33,018 cekit        DEBUG    Preparing module 'a' requested by 'testimage'.
2018-10-19 08:35:33,018 cekit        DEBUG    Loading descriptor from path 'target/image/modules/a/module.yaml'.

Traceback (most recent call last):
  File "/usr/bin/cekit", line 9, in <module>
    load_entry_point('cekit==2.1.4', 'console_scripts', 'cekit')()
  File "/usr/lib/python2.7/site-packages/cekit/cli.py", line 283, in run
    Cekit().parse().run()
  File "/usr/lib/python2.7/site-packages/cekit/cli.py", line 222, in run
    generator.prepare_modules()
  File "/usr/lib/python2.7/site-packages/cekit/generator/base.py", line 102, in prepare_modules
    os.path.join(self.target, 'image', 'modules'))
  File "/usr/lib/python2.7/site-packages/cekit/module.py", line 40, in copy_module_to_target
    check_module_version(dest, version)
  File "/usr/lib/python2.7/site-packages/cekit/module.py", line 54, in check_module_version
    if descriptor.version != version:
AttributeError: 'Module' object has no attribute 'version'
```

**Comment by jmtd** [comment]
Here's a ZIP of the test YAMLs to make reproducing easier
[322.zip](https://github.com/cekit/cekit/files/2514444/322.zip)
