### ISSUE TITLE
Fetching ODCS repos sometimes fails

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#351]
```
[37m2019-01-03 10:53:03,596 cekit        DEBUG    Creating ODCS content set via 'odcs --redhat create pulp rhel-7-server-rpms'[0m
[32m2019-01-03 10:53:10,634 cekit        INFO     Preparing resource 'odcs-45278.repo'[0m
[37m2019-01-03 10:53:10,634 cekit        DEBUG    Downloading from 'http://REDACTED/composes/latest-odcs-45278-1/compose/Temporary/odcs-45278.repo' as target/image/repos/content_sets_odcs.repo[0m
[37m2019-01-03 10:53:10,646 cekit        DEBUG    Cannot hit artifact: 'odcs-45278.repo' via cacher, trying directly.[0m
[37m2019-01-03 10:53:10,646 cekit        DEBUG    Downloading from 'http://REDACTED/composes/latest-odcs-45278-1/compose/Temporary/odcs-45278.repo' as target/image/repos/content_sets_odcs.repo[0m
[33m2019-01-03 10:53:10,654 cekit        WARNING  Cekit is not able to fetch resource 'odcs-45278.repo' automatically. Please use cekit-cache command to add this artifact manually.[0m
[31m2019-01-03 10:53:10,654 cekit        ERROR    ("Error copying resource: 'odcs-45278.repo'. See logs for more info.", HTTPError())
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cekit/cli.py", line 225, in run
    generator.generate()
  File "/usr/lib/python2.7/site-packages/cekit/generator/base.py", line 86, in generate
    self.prepare_repositories()
  File "/usr/lib/python2.7/site-packages/cekit/generator/base.py", line 340, in prepare_repositories
    repo.fetch(os.path.join(self.target, 'image', 'repos'))
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/packages.py", line 177, in fetch
    .copy(os.path.join(target_dir, self._descriptor['filename']))
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/resource.py", line 115, in copy
    return self.guarded_copy(target)
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/resource.py", line 129, in guarded_copy
    % self.name, ex)
CekitError: ("Error copying resource: 'odcs-45278.repo'. See logs for more info.", HTTPError())[0m
```

**Comment by goldmann** [comment]
The URL is accessible via browser and the correct content is returned. Maybe we try to hit it too fast? Or maybe it's related to multiple requests sent at the same time?

**Comment by goldmann** [comment]
I cannot reproduce it locally, it must be related to the CI setup.

**Comment by goldmann** [comment]
It may be also related to Python 3 (used locally) vs. Python 2 (used on CI) incompatibility.

**Comment by goldmann** [comment]
The real issue was that the proxy in the CI environment, squid, which I forgot about, misbehaved after a node failure. It lost connection to the DNS which resulted in timeouts and made it impossible to serve the request.
