### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys' when using old type repositories

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#385]
```
2019-02-14 09:50:20,632 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
Traceback (most recent call last):
  File "/usr/bin/cekit", line 11, in <module>
    load_entry_point('cekit==2.2.5', 'console_scripts', 'cekit')()
  File "/usr/lib/python3.7/site-packages/cekit/cli.py", line 289, in run
    Cekit().parse().run()
  File "/usr/lib/python3.7/site-packages/cekit/cli.py", line 223, in run
    discover_modules(os.path.join(self.args.target, 'repo'))
  File "/usr/lib/python3.7/site-packages/cekit/module.py", line 92, in discover_modules
    'module.yaml'))))
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/module.py", line 31, in __init__
    self._prepare()
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/image.py", line 89, in _prepare
    self._descriptor['packages'] = Packages(self._descriptor['packages'])
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/packages.py", line 59, in __init__
    self._prepare()
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/packages.py", line 63, in _prepare
    for x in self._descriptor.get('repositories', [])]
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/packages.py", line 63, in <listcomp>
    for x in self._descriptor.get('repositories', [])]
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/packages.py", line 77, in __init__
    descriptor = self._create_repo_object(descriptor)
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/packages.py", line 112, in _create_repo_object
    descriptor['url']['repository'] = self._get_repo_url(descriptor)
  File "/usr/lib/python3.7/site-packages/cekit/descriptor/packages.py", line 121, in _get_repo_url
    configured_repository_names = configured_repositories.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by goldmann** [comment]
This happens when the old repository is used in the image descriptor, but it's not defined in the Cekit configuration file. We should probably remove support for this old types of repositories for 3.0.

**Comment by goldmann** [comment]
This affects 2.2.5, the 3.0 version does not have this issue.

**Comment by goldmann** [comment]
It was already reported for develop: https://github.com/cekit/cekit/issues/344 and fixed via this PR: https://github.com/cekit/cekit/pull/346. It needs to be backported to master.

**Comment by goldmann** [comment]
Commit 2a1c74499105f4c1bd920062a56f027702fd4872 was cherry picked to master as 0b7d15f8a365129a1321ab81c2aba2f7b74a9805.
