### ISSUE TITLE
Detect and handle docker daemon not running

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#387]
Currently I get this trace out: ; I think it should be handled better.
```
    2019-02-14 09:35:39,961 cekit        INFO     Preparing resource 'odcs-60967.repo'
    2019-02-14 09:35:40,289 cekit        INFO     Handling artifacts...
    2019-02-14 09:35:40,289 cekit        INFO     Preparing resource 'hawkular-javaagent'
    2019-02-14 09:35:40,313 cekit        INFO     Preparing resource 'jolokia-jvm-1.5.0.redhat-1-agent.jar'
    2019-02-14 09:35:40,315 cekit        INFO     Preparing resource 'jmx_prometheus_javaagent'
    2019-02-14 09:35:40,316 cekit        INFO     Rendering Dockerfile...
    2019-02-14 09:35:40,434 cekit        INFO     Using Docker builder to build the image.
    2019-02-14 09:35:40,434 cekit        INFO     Building container image...
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib64/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
        self.send(msg)
      File "/usr/lib64/python3.7/http/client.py", line 956, in send
        self.connect()
      File "/usr/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
        sock.connect(self.unix_socket)
    FileNotFoundError: [Errno 2] No such file or directory
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 692, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib64/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
        self.send(msg)
      File "/usr/lib64/python3.7/http/client.py", line 956, in send
        self.connect()
      File "/usr/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
        sock.connect(self.unix_socket)
    urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "/home/rnc/.virtualenvs/cekit/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 98, in build
        out = self.docker_client.build(**args)
      File "/usr/lib/python3.7/site-packages/docker/api/build.py", line 259, in build
        timeout=timeout,
      File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
        return f(self, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 194, in _post
        return self.post(url, **self._set_request_timeout(kwargs))
      File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 572, in post
        return self.request('POST', url, data=data, json=json, **kwargs)
      File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "/home/rnc/.virtualenvs/cekit/bin/cekit", line 10, in <module>
        sys.exit(run())
      File "/home/rnc/.virtualenvs/cekit/lib/python3.7/site-packages/cekit/cli.py", line 303, in run
        Cekit().parse().run()
      File "/home/rnc/.virtualenvs/cekit/lib/python3.7/site-packages/cekit/cli.py", line 265, in run
        builder.build()
      File "/home/rnc/.virtualenvs/cekit/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 139, in build
        if "To enable Red Hat Subscription Management repositories:" in ' '.join(build_log) and \
    UnboundLocalError: local variable 'build_log' referenced before assignment
``

**Comment by goldmann** [comment]
Fixed via #399.
