### ISSUE TITLE
OSBS builder doesn't work well with plain artifacts with target set

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#414]
It uses the `name` attribute instead of `target` if available.

**Comment by goldmann** [comment]
Full traceback:

```
Traceback (most recent call last):
  File "/usr/bin/cekit", line 11, in <module>
    load_entry_point('cekit==2.2.6', 'console_scripts', 'cekit')()
  File "/usr/lib/python3.7/site-packages/cekit/cli.py", line 289, in run
    Cekit().parse().run()
  File "/usr/lib/python3.7/site-packages/cekit/cli.py", line 255, in run
    builder.prepare(generator.image)
  File "/usr/lib/python3.7/site-packages/cekit/builders/osbs.py", line 94, in prepare
    self.update_osbs_image_source()
  File "/usr/lib/python3.7/site-packages/cekit/builders/osbs.py", line 119, in update_osbs_image_source
    artifact))
  File "/usr/lib64/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'target/image/jboss-dv-6.4.6-patch'
```

**Comment by goldmann** [comment]
And similar traceback from development branch:

```
Traceback (most recent call last):
  File "/home/goldmann/git/redhat/cekit/venv/bin/cekit", line 11, in <module>
    load_entry_point('cekit', 'console_scripts', 'cekit')()
  File "/home/goldmann/git/redhat/cekit/cekit/cli.py", line 309, in run
    Cekit().parse().run()
  File "/home/goldmann/git/redhat/cekit/cekit/cli.py", line 270, in run
    builder.prepare(self.generator.image)
  File "/home/goldmann/git/redhat/cekit/cekit/builders/osbs.py", line 130, in prepare
    self.update_osbs_image_source()
  File "/home/goldmann/git/redhat/cekit/cekit/builders/osbs.py", line 155, in update_osbs_image_source
    artifact))
  File "/home/goldmann/git/redhat/cekit/venv/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/goldmann/git/redhat/cekit/venv/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'target/image/jboss-dv-6.4.6-patch'
```

**Comment by goldmann** [comment]
The issue is in these lines: https://github.com/cekit/cekit/blob/465639868991cca6a6db532623d7ef5d538675d0/cekit/builders/osbs.py#L119-L124. These have hardcoded `name` key. Instead, this function should be used: https://github.com/cekit/cekit/blob/465639868991cca6a6db532623d7ef5d538675d0/cekit/descriptor/resource.py#L86-L89
