### ISSUE TITLE
Improve removal of elements in descriptors

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#460]
We can remove elements by specifying their value to `null`. In case the element has a schema value `required` set to `True`, removal will not work:

```
2019-03-27 16:10:36,198 cekit        DEBUG    Loading override '{"labels": [{"name": "usage", "value": "aaa"}]}'
2019-03-27 16:10:36,198 cekit        DEBUG    Reading descriptor directly...
2019-03-27 16:10:36,199 cekit        DEBUG    Loading override '{"labels": [{"name": "usage", "value": null}]}'
2019-03-27 16:10:36,200 cekit        DEBUG    Reading descriptor directly...
No handlers could be found for logger "pykwalify.core"
2019-03-27 16:10:36,200 cekit        DEBUG    Schema validation failed: <SchemaError: error code 2: Schema validation failed:
 - required.novalue : '/value'.: Path: '/'>
2019-03-27 16:10:36,200 cekit        ERROR    Cannot validate schema: Label
Traceback (most recent call last):
  File "/home/goldmann/git/redhat/cekit/cekit/cli.py", line 336, in run
    command.execute()
  File "/home/goldmann/git/redhat/cekit/cekit/builder.py", line 53, in execute
    self.prepare()
  File "/home/goldmann/git/redhat/cekit/cekit/builder.py", line 74, in prepare
    self.params.overrides)
  File "/home/goldmann/git/redhat/cekit/cekit/generator/docker.py", line 21, in __init__
    super(DockerGenerator, self).__init__(descriptor_path, target, overrides)
  File "/home/goldmann/git/redhat/cekit/cekit/generator/base.py", line 46, in __init__
    override), os.path.dirname(os.path.abspath(override))))
  File "/home/goldmann/git/redhat/cekit/cekit/descriptor/overrides.py", line 18, in __init__
    self._prepare()
  File "/home/goldmann/git/redhat/cekit/cekit/descriptor/image.py", line 53, in _prepare
    self._descriptor['labels'] = [Label(x) for x in self._descriptor.get('labels', [])]
  File "/home/goldmann/git/redhat/cekit/cekit/descriptor/label.py", line 21, in __init__
    super(Label, self).__init__(descriptor)
  File "/home/goldmann/git/redhat/cekit/cekit/descriptor/base.py", line 36, in __init__
    self.__validate()
  File "/home/goldmann/git/redhat/cekit/cekit/descriptor/base.py", line 49, in __validate
    raise CekitError("Cannot validate schema: %s" % (self.__class__.__name__))
CekitError: Cannot validate schema: Label
```

**Comment by rnc** [comment]
Looking at this, even **if** the label value is optional, then it appears that we don't support removal in the current codebase. From looking at descriptor/image.py::apply_image_overrides there would need to be some thought on how that could work. By default 'no value' is `None` which is the same as what e.g. `description: ~` evaluates to ; this therefore makes it difficult to disinguish between removing a value and the non-existence of a value being defined within the overrides. This is similar to #402 so I'll close this one in favour of that.
