### ISSUE TITLE
Cleaning directory tree leads to obscure error

### ISSUE THREAD

**Issue by rnc** [cekit/cekit#468]
**Describe the solution you'd like**
Currently when building, if the current user does not have permission to remove the directory tree you get
```
2019-04-04 14:37:25,285 cekit        DEBUG    Configuring CEKit...
2019-04-04 14:37:25,286 cekit        DEBUG    Removing dirty directory: 'target/image/modules'
Traceback (most recent call last):
  File "/home/rnc/.virtualenvs/cekit/bin/cekit", line 11, in <module>
    load_entry_point('cekit', 'console_scripts', 'cekit')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rnc/Work/CEKit/GitHub/cekit/cekit/cli.py", line 136, in build_podman
    run_build(ctx, 'podman')
  File "/home/rnc/Work/CEKit/GitHub/cekit/cekit/cli.py", line 280, in run_build
    run_command(ctx, builder_impl)
  File "/home/rnc/Work/CEKit/GitHub/cekit/cekit/cli.py", line 249, in run_command
    Cekit(common_params).run(clazz, params)
  File "/home/rnc/Work/CEKit/GitHub/cekit/cekit/cli.py", line 331, in run
    self.cleanup()
  File "/home/rnc/Work/CEKit/GitHub/cekit/cekit/cli.py", line 324, in cleanup
    shutil.rmtree(directory)
  File "/home/rnc/.virtualenvs/cekit/lib64/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/rnc/.virtualenvs/cekit/lib64/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/rnc/.virtualenvs/cekit/lib64/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/rnc/.virtualenvs/cekit/lib64/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'install.sh'
```

**Additional context**
I think it would be better to wrap that in a try/except so you get an error like
```
cekit.errors.CekitError: Unable to clean directory 'target/image/modules'
```

**Comment by goldmann** [comment]
This should never happen. For me it looks like someone executed CEKit with sudo or something similar. Could that be the case?

**Comment by rnc** [comment]
It was because a prior invocation in the same area had used sudo - to build with docker - and the current invocation was not using sudo and using podman.

**Comment by goldmann** [comment]
Sure, I'm fine with such enhancement.

BTW, you should never run cekit with `sudo`. Docker needs to be configured to run as user.

```
$ sudo groupadd docker && sudo gpasswd -a ${USER} docker && sudo systemctl restart docker
$ newgrp docker
```
