### ISSUE TITLE
docker build cannot handle more than one colon passed to the --tag option

### ISSUE THREAD

**Issue by errantepiphany** [cekit/cekit#508]
**Describe the bug**
When passing more than one colon in the value for docker --tag, cekit will throw an error. This bug does not exist in 2.7, but does in 3.0.

**To reproduce**
This will fail:
`cekit build --overrides-file branch-overrides.yaml docker --tag 172.30.1.1:5000/dward/rhdm74-kieserver:7.4.0`

However, this will pass:
`cekit build --overrides-file branch-overrides.yaml docker --tag 172.30.1.1/dward/rhdm74-kieserver:7.4.0`
as will this:
`cekit build --overrides-file branch-overrides.yaml docker --tag dward/rhdm74-kieserver:7.4.0`

It's the colon for the port that is unexpected.

**Expected behavior**
No matter how many colons are in it, cekit should be able to tag the docker-built image with the tag provided.

**Logs**
Traceback (most recent call last):
```
  File "/home/dward/Packages/cekit/3.0/bin/cekit", line 10, in <module>
    sys.exit(cli())
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/cli.py", line 106, in build_docker
    run_build(ctx, 'docker')
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/cli.py", line 282, in run_build
    run_command(ctx, builder_impl)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/cli.py", line 251, in run_command
    Cekit(common_params).run(clazz, params)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/cli.py", line 341, in run
    command.execute()
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/builder.py", line 60, in execute
    self.run()
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 189, in run
    self._tag(docker_client, image_id, tags)
  File "/home/dward/Packages/cekit/3.0/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 165, in _tag
    img_repo, img_tag = tag.split(":")
ValueError: too many values to unpack (expected 2)
```

This is the key part:
**img_repo, img_tag = tag.split(":") ValueError: too many values to unpack (expected 2)**

**Environment information:**
 - Operating system: Fedora 29 (Linux 5.0.10-200.fc29.x86_64)
 - CEKit version: Result of `cekit --version` 3.0.1 (pip3)

**Comment by goldmann** [comment]
I can confirm this, fix will be submitted shortly.

**Comment by errantepiphany** [comment]
Thanks @goldmann
