### ISSUE TITLE
 ERROR    Cannot validate schema: Repository

### ISSUE THREAD

**Issue by uocxp** [cekit/cekit#524]
I am trying to build[ jboss-amq-7-broker-openshift-image](https://github.com/jboss-container-images/jboss-amq-7-broker-openshift-image.git) using cekit 3.0.1 on Centos 7 but i am getting 
```
2019-05-27 16:24:28,185 cekit        INFO     You are running on known platform: CentOS Linux 7 (Core)
2019-05-27 16:24:28,216 cekit        INFO     Generating files for docker engine
2019-05-27 16:24:28,216 cekit        INFO     Initializing image descriptor...
No handlers could be found for logger "pykwalify.core"
2019-05-27 16:24:28,252 cekit        ERROR    Cannot validate schema: Repository
```
i am excuting `cekit build docker` inside the directory.
Am i missing something here ?

**Comment by goldmann** [comment]
Can you please run it with `--verbose` switch?

**Comment by uocxp** [comment]
```
2019-05-27 16:31:41,911 cekit        DEBUG    Running version 3.0.1
2019-05-27 16:31:41,911 cekit        DEBUG    Configuring CEKit...
2019-05-27 16:31:41,912 cekit        INFO     You are running on known platform: CentOS Linux 7 (Core)
2019-05-27 16:31:41,912 cekit        DEBUG    Checking CEKit core dependencies...
2019-05-27 16:31:41,912 cekit        DEBUG    Checking if 'git' dependency is provided...
2019-05-27 16:31:41,912 cekit        DEBUG    CEKit dependency 'git' provided via the '/usr/bin/git' executable.
2019-05-27 16:31:41,912 cekit        DEBUG    All dependencies provided!
2019-05-27 16:31:41,943 cekit        INFO     Generating files for docker engine
2019-05-27 16:31:41,943 cekit        INFO     Initializing image descriptor...
2019-05-27 16:31:41,943 cekit        DEBUG    Checking CEKit generate dependencies...
2019-05-27 16:31:41,943 cekit        DEBUG    No dependencies found, skipping...
2019-05-27 16:31:41,944 cekit        DEBUG    Reading descriptor from 'image.yaml' file...
No handlers could be found for logger "pykwalify.core"
2019-05-27 16:31:41,979 cekit        DEBUG    Schema validation failed: <SchemaError: error code 2: Schema validation failed:
 - Value 'jboss-os' is not a dict. Value path: ''.: Path: '/'>
2019-05-27 16:31:41,979 cekit        ERROR    Cannot validate schema: Repository
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cekit/cli.py", line 341, in run
    command.execute()
  File "/usr/lib/python2.7/site-packages/cekit/builder.py", line 53, in execute
    self.prepare()
  File "/usr/lib/python2.7/site-packages/cekit/builder.py", line 88, in prepare
    self.generator.init()
  File "/usr/lib/python2.7/site-packages/cekit/generator/base.py", line 61, in init
    self.image = Image(descriptor, os.path.dirname(os.path.abspath(self._descriptor_path)))
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/image.py", line 50, in __init__
    self._prepare()
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/image.py", line 61, in _prepare
    self._descriptor['packages'] = Packages(self._descriptor.get('packages', {}), self.path)
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/packages.py", line 68, in __init__
    self._prepare()
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/packages.py", line 72, in _prepare
    for x in self._descriptor.get('repositories', [])]
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/packages.py", line 116, in __init__
    super(Repository, self).__init__(descriptor)
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/base.py", line 36, in __init__
    self.__validate()
  File "/usr/lib/python2.7/site-packages/cekit/descriptor/base.py", line 49, in __validate
    raise CekitError("Cannot validate schema: %s" % (self.__class__.__name__))
CekitError: Cannot validate schema: Repository
```

**Comment by goldmann** [comment]
```
 - Value 'jboss-os' is not a dict. Value path: ''.: Path: '/'>
```

Usage of old type repositories was removed in CEKit 3.x.

Release notes: https://github.com/cekit/cekit/releases/tag/3.0.0
Issue: https://github.com/cekit/cekit/issues/386

You probably want to talk to the image owner.

**Comment by uocxp** [comment]
Thanks a lot ! I will open an issue there.

**Comment by goldmann** [comment]
You can potentially open a CLOUD issue: https://issues.jboss.org/browse/CLOUD Or open one in RH Bugzilla for this specific product.

I'm closing this ticket because this is not a CEKit issue and more an image problem.
