### ISSUE TITLE
Add a command line argument to define the temporal folder

### ISSUE THREAD

**Issue by yersan** [cekit/cekit#525]
I'm running out of space very often when I use Cekit without --no-squash, I don't know if there is already a solution to define the folder I want to use as /tmp when I build an image, but I think it could be useful to be able to define it via the build command itself, something like:

cekit build --temp=/mnt/shared/folder docker

Do you see it useful?, In my case, if I can send all the images generated internally by Cekit to an external folder, my space issue will be fixed

**Comment by goldmann** [comment]
Can you please paste example failure log? There  are multiple temporary directories that could affect your build. I wonder which one is hitting you.

**Comment by goldmann** [comment]
Are you sure you are not hit by the Docker daemon temporary directory space issue? See `DOCKER_TMPDIR` here: https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by yersan** [comment]
Usually, I see this error:

`2019-05-28 10:22:18,790 cekit        INFO     Saving image sha256:c20d34fc32b6b79a148164b2c9f85bfac62d0a96a358bdba7ced71db9d326f83 to /tmp/docker-squash-tAYzEd/old directory...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/opt/rh/python27/root/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/docker_squash/image.py", line 341, in _extract_tar
    tar.extractall(path=directory)
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 2235, in makefile
    copyfileobj(source, target)
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/opt/rh/python27/root/usr/lib64/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
`

> Are you sure you are not hit by the Docker daemon temporary directory space issue? See DOCKER_TMPDIR here: https://docs.docker.com/engine/reference/commandline/dockerd/

I've configured the docker temporal dir as you suggested (thanks!), I can see how some images are stored there, however, I still see a /tmp/docker-squash-xxxxx folder that requires around 3,5 Gb in my build, so it is not enough in my case the uses of DOCKER_TMPDIR. I haven't found how to configure a different temporal folder for the docker-squash, do you know if that's possible?

**Comment by goldmann** [comment]
OK, now it's clear what the issue is. You should be able to specify the temporary directory by just specifying the `TMPDIR` environment variable, like this:

```
TMPDIR=/opt/squash cekit -v build docker
```

**Comment by goldmann** [comment]
To track an enhancement in the documentation I created this issue: https://github.com/cekit/cekit/issues/526.

**Comment by yersan** [comment]
The uses of TMPDIR environment variable works and I can see how docker-squash-xxx folder is created under my TMPDIR folder. However, at least creating the EAP images, the Cekit build fails with an error:

`2019-05-28 14:55:40,703 cekit        INFO     Squashing file '/home/yborgess/tmp/docker-squash-2d7ib7/old/858dcab4cd58af7dc3d9a6827a6bbff08347c292cbd2edb302fda34d93e83582/layer.tar'...
2019-05-28 14:55:40,703 cekit        DEBUG    Cleaning up /home/yborgess/tmp/docker-squash-2d7ib7 temporary directory
Traceback (most recent call last):
  File "/home/yborgess/cekit-3/bin/cekit", line 11, in <module>
    sys.exit(cli())
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/cli.py", line 106, in build_docker
    run_build(ctx, 'docker')
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/cli.py", line 282, in run_build
    run_command(ctx, builder_impl)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/cli.py", line 251, in run_command
    Cekit(common_params).run(clazz, params)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/cli.py", line 341, in run
    command.execute()
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/builder.py", line 60, in execute
    self.run()
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/builders/docker_builder.py", line 186, in run
    image_id = self._squash(docker_client, image_id)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/cekit/builders/docker_builder.py", line 160, in _squash
    return squash.run()
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/docker_squash/squash.py", line 59, in run
    return self.squash(image)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/docker_squash/squash.py", line 82, in squash
    new_image_id = image.squash()
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/docker_squash/image.py", line 74, in squash
    ret = self._squash()
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/docker_squash/v2_image.py", line 40, in _squash
    self.layer_paths_to_move)
  File "/home/yborgess/cekit-3/lib/python2.7/site-packages/docker_squash/image.py", line 719, in _squash_layers
    with tarfile.open(layer_tar_file, 'r', format=tarfile.PAX_FORMAT) as layer_tar:
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "/opt/rh/python27/root/usr/lib64/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/opt/rh/python27/root/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: u'/home/yborgess/tmp/docker-squash-2d7ib7/old/858dcab4cd58af7dc3d9a6827a6bbff08347c292cbd2edb302fda34d93e83582/layer.tar'`

I've checked the build output and I cannot see a log trace pointing out the missing image was copied to the docker-squash-2d7ib7 folder.

**Comment by goldmann** [comment]
Could you please point me to the image source you are trying to build and the command you used to build it? I'll try to reproduce it locally.

**Comment by yersan** [comment]
I'm building https://github.com/jboss-container-images/jboss-eap-7-image. 

It seems it is working fine now, I'm not sure where the problem was before, I had TMPDIR and DOCKER_TMPDIR pointing both to different folders. I change them, pointing to the same folder and it worked. I thought maybe the problem was due to the different location of both variables, so I change them again but now, even having both pointing to different folders, it works.

I really don't know exctly why was failing before.

**Comment by yersan** [comment]
I'm going to close the ticket and I'll reopen if I see the same error, and have a reproducible way. Thanks for the support Marek
