### ISSUE TITLE
Formatting issue in module example in documentation

### ISSUE THREAD

**Issue by cmoulliard** [cekit/cekit#535]
## Issue

The tomcat example as proposed within the [doc](https://cekit.readthedocs.io/en/latest/getting-started/modules.html) is wrong

```
name: tomcat
version: 1.0
description: "Module used to install Tomcat 8"
# Defined artifacts that are used to build the image
artifacts:
  - name: tomcat.tar.gz
      url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.24/bin/apache-tomcat-8.5.24.tar.gz
      md5: 080075877a66adf52b7f6d0013fa9730
execute:
  - script: install.sh

run:
  cmd:
    - "/home/user/apache-tomcat-8.5.24/bin/catalina.sh"
    - "run"
```

When it is processed by the command `cekit build podman` using cekit 3.1, then we will get this error

```
cekit build podman
2019-06-07 17:14:18,348 cekit        WARNING  You are running CEKit on an unknown platform. External dependencies suggestions may not work!
2019-06-07 17:14:18,763 cekit        INFO     Generating files for podman engine
2019-06-07 17:14:18,763 cekit        INFO     Initializing image descriptor...
2019-06-07 17:14:18,783 cekit        INFO     Preparing resource 'modules'
Traceback (most recent call last):
  File "/Users/dabou/cekit/bin/cekit", line 10, in <module>
    sys.exit(cli())
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/cli.py", line 136, in build_podman
    run_build(ctx, 'podman')
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/cli.py", line 282, in run_build
    run_command(ctx, builder_impl)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/cli.py", line 251, in run_command
    Cekit(common_params).run(clazz, params)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/cli.py", line 341, in run
    command.execute()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/builder.py", line 53, in execute
    self.prepare()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/builder.py", line 88, in prepare
    self.generator.init()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/generator/base.py", line 99, in init
    self.build_module_registry()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/generator/base.py", line 155, in build_module_registry
    self.load_repository(os.path.join(base_dir, repo.target_file_name()))
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/generator/base.py", line 164, in load_repository
    module = Module(tools.load_descriptor(module_descriptor_path),
  File "/Users/dabou/cekit/lib/python3.7/site-packages/cekit/tools.py", line 51, in load_descriptor
    return yaml.safe_load(fh)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/Users/dabou/cekit/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/Users/dabou/Temp/cekit-test/target/repo/modules/tomcat/module.yaml", line 7, column 10
```

**Comment by goldmann** [comment]
It looks like a formatting issue, I'll fix it. Thank you!

Here is how it should look: https://github.com/cekit/example-image-tomcat/blob/master/modules/tomcat/module.yaml
