### ISSUE TITLE
Docker output encoding issues with Python 2.7

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#538]
**Describe the bug**
While building Docker image on macOS with Python 2.7 an encoding issue occurs:

**To reproduce**
Image used to build this image: https://github.com/wildfly/wildfly-s2i/tree/master/wildfly-builder-image

**Expected behavior**
No error.

**Logs**
```
2019-06-07 16:24:33,607 cekit        ERROR    You can look inside the failed image by running 'docker run --rm -ti bf2f9147dafb bash'
2019-06-07 16:24:33,607 cekit        ERROR    ('Image build failed, see logs above.', UnicodeEncodeError('ascii', u'Step 96/104 : LABEL       description="The WildFly s2i image"        io.cekit.version="3.1.0"        io.k8s.description="Platform for building and running JEE applications on WildFly $WILDFLY_VERSION"        io.k8s.display-name="WildFly $WILDFLY_VERSION"        io.openshift.expose-services="8080:http,8778:jolokia"        io.openshift.tags="builder,wildfly,wildfly17"        maintainer="Jean-Fran\xe7ois Denise <REDACTED@REDACTED.com>"        name="wildfly/wildfly-centos7"        summary="The WildFly s2i image"        version="dev"', 397, 398, 'ordinal not in range(128)'))
Traceback (most recent call last):
  File "/Users/jmesnil/cekit/lib/python2.7/site-packages/cekit/cli.py", line 341, in run
    command.execute()
  File "/Users/jmesnil/cekit/lib/python2.7/site-packages/cekit/builder.py", line 60, in execute
    self.run()
  File "/Users/jmesnil/cekit/lib/python2.7/site-packages/cekit/builders/docker_builder.py", line 191, in run
    image_id = self._build_with_docker(docker_client)
  File "/Users/jmesnil/cekit/lib/python2.7/site-packages/cekit/builders/docker_builder.py", line 157, in _build_with_docker
    raise CekitError(msg, ex)
CekitError: ('Image build failed, see logs above.', UnicodeEncodeError('ascii', u'Step 96/104 : LABEL       description="The WildFly s2i image"        io.cekit.version="3.1.0"        io.k8s.description="Platform for building and running JEE applications on WildFly $WILDFLY_VERSION"        io.k8s.display-name="WildFly $WILDFLY_VERSION"        io.openshift.expose-services="8080:http,8778:jolokia"        io.openshift.tags="builder,wildfly,wildfly17"        maintainer="Jean-Fran\xe7ois Denise <REDACTED@REDACTED.com>"        name="wildfly/wildfly-centos7"        summary="The WildFly s2i image"        version="dev"', 397, 398, 'ordinal not in range(128)'))
```

**Environment information:**
 - macOS
 - CEKit 3.1
- Python 2.7

**Additional context**
None.

**Comment by goldmann** [comment]
@jfdenise I could reproduce it on our CI: https://circleci.com/gh/cekit/cekit/1285 on Linux platform. I'll work on a fix for this.
