### ISSUE TITLE
microdnf issue when installing packages from module.yaml and image.yaml

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#552]
**Describe the bug**
PS: Opened for investigation, not sure if it is a CEKit or microdnf issue.
Executing the microdnf commands separately like from generated Dockerfile inside the ubi8-minimal image, didn't reproduce the error:
microdnf --setopt=tsflags=nodocs install -y shadow-utils   && rpm -q shadow-utils
microdnf --setopt=tsflags=nodocs install -y java-11-openjdk   && rpm -q java-11-openjdk
microdnf --setopt=tsflags=nodocs install -y git   && rpm -q git

When a image contains packages to be installed by microdnf in a module and in the image.yaml, it will fail.

A workaround would be have a module to install app needed rpms, like:
```
schema_version: 1
name: install-rpm-dependencies

packages:
  install:
    - shadow-utils
    - git
    - java-11-openjdk
```

**To reproduce**
Build a image which contains a module that install a package using microdnf and add another package on the main image.yaml descriptor:

structure:
```
cekit-modules/
└── java-openjdk
    └── 11
        └── module.yaml
```
module.yaml content:

```
schema_version: 1
name: java-openjdk
version: "11"

labels:
  - name: "com.redhat.component"
    value: "jboss-openjdk18-rhel7-container"
  - name: "org.jboss.product"
    value: "openjdk"
  - name: "org.jboss.product.version"
    value: "11.0"
  - name: "org.jboss.product.openjdk.version"
    value: "11.0"

envs:
  - name: "JAVA_HOME"
    value: "/usr/lib/jvm/java-11"
  - name: "JAVA_VENDOR"
    value: "openjdk"
  - name: "JAVA_VERSION"
    value: "11.0"

packages:
  manager: microdnf
  install:
  - java-11-openjdk
```

image.yaml content:
```
schema_version: 1

name: "test"
version: "1.0"
from: "registry.redhat.io/ubi8-minimal:latest"

labels:
  - name: "io.openshift.expose-services"
    value: "8080:http"

modules:
  repositories:
    - path: cekit-modules
  install:
    - name: java-openjdk
      version: "11"

packages:
  manager: microdnf
  install:
    - git
    - java-11-openjdk

run:
  user: 1001
  cmd:
    - "ls -la"
```

**Expected behavior**
A successful microdnf installation is expected of all packages, configured in the modules or in the main image.yaml descriptor.

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.

```
2019-06-26 18:00:42,591 cekit        INFO     Docker: Downloading metadata...
2019-06-26 18:00:46,516 cekit        INFO     Docker: error: cannot move /var/cache/yum/metadata/ubi-8-baseos-8-x86_64/packages to /var/cache/yum/metadata/ubi-8-baseos-8-x86_64.tmp/packages
2019-06-26 18:00:46,673 cekit        ERROR    You can look inside the failed image by running 'docker run --rm -ti e6fc05bd4fd3 bash'
2019-06-26 18:00:46,673 cekit        ERROR    ('Image build failed, see logs above.', CekitError("Image build failed: 'The command '/bin/sh -c microdnf --setopt=tsflags=nodocs install -y git     && rpm -q git' returned a non-zero code: 1'"))
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 88, in _build_with_docker
    raise CekitError("Image build failed: '{}'".format(error_message))
cekit.errors.CekitError: Image build failed: 'The command '/bin/sh -c microdnf --setopt=tsflags=nodocs install -y git     && rpm -q git' returned a non-zero code: 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cekit/cli.py", line 341, in run
    command.execute()
  File "/usr/lib/python3.7/site-packages/cekit/builder.py", line 67, in execute
    self.run()
  File "/usr/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 241, in run
    image_id = self._build_with_docker(docker_client)
  File "/usr/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 149, in _build_with_docker
    raise CekitError(msg, ex)
cekit.errors.CekitError: ('Image build failed, see logs above.', CekitError("Image build failed: 'The command '/bin/sh -c microdnf --setopt=tsflags=nodocs install -y git     && rpm -q git' returned a non-zero code: 1'"))
```

**Environment information:**
 - Operating system: Fedora release 30 (Thirty)
 - CEKit version: Result of `cekit --version`: 3.2.0

**Comment by goldmann** [comment]
This is a microdnf issue which is reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1700341

Related ticket: https://github.com/cekit/cekit/issues/485.

**Comment by goldmann** [comment]
@spolti I suggest to add a comment to the ticket above. Unfortunately it does not have enough attention.

I'll close this ticket now.

**Comment by spolti** [comment]
@goldmann thanks for the info, added a comment there.
