### ISSUE TITLE
certificate/certifi handling issues

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#606]
**Describe the bug**
I'm getting SSL verify problems for an internal ODCS host with cekit 3.3.1.

```
(3.3.1) 🎩︎ cekit -v --redhat build --overrides-file rhel8-jdk11-overrides.yaml docker
…
2019-09-02 11:32:29,278 cekit        WARNING  The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2019-09-02 11:32:29,278 cekit        WARNING  Certificate Authority (CA) bundle in use: '/home/ce/cekit/3.3.1/lib/python2.7/site-packages/certifi/cacert.pem'
…
2019-09-02 11:32:30,312 cekit        DEBUG    Requesting ODCS pulp compose for 'rhel-8-for-x86_64-baseos-rpms rhel-8-for-x86_64-appstream-rpms' repositories with '['include_unpublished_pulp_repos']' flags...
…
requests.exceptions.SSLError: HTTPSConnectionPool(host='[REDACTED]', port=443): Max retries exceeded with url: /api/1/composes/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

The above log messages suggest

 * I don't have certifi installed
 * it's using my system CA trust, but at the same time
 * using a ca bundle in a private path (contradiction)

And I can verify that my system CA trust is fine for this host:

```
(3.3.1) 🎩︎  openssl s_client -connect [REDACTED]:443
…
    Verify return code: 0 (ok)
…
```

And I do have certifi installed, anyway:

```
(3.3.1) 🎩︎ pip install certifi                                      
Requirement already satisfied: certifi in /home/ce/cekit/3.3.1/lib/python2.7/site-packages
```

I can reproduce this with 3.2.0 and 3.4.0 but not 3.0.0.

**Logs**

Full traceback, elided above for clarity

```
2019-09-02 11:32:30,312 cekit        DEBUG    Requesting ODCS pulp compose for 'rhel-8-for-x86_64-baseos-rpms rhel-8-for-x86_64-appstream-rpms' repositories with '['include_unpublished_pulp_repos']' flags...
Traceback (most recent call last):
  File "/home/ce/cekit/3.3.1/bin/cekit", line 11, in <module>
    load_entry_point('cekit==3.3.1', 'console_scripts', 'cekit')()
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/cli.py", line 107, in build_docker
    run_build(ctx, 'docker')
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/cli.py", line 275, in run_build
    run_command(ctx, builder_impl)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/cli.py", line 244, in run_command
    Cekit(params).run(clazz)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/cli.py", line 334, in run
    command.execute()
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/builder.py", line 59, in execute
    self.generate()
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/builder.py", line 98, in generate
    self.generator.generate(self.build_engine)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/generator/base.py", line 109, in generate
    self.prepare_repositories()
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/generator/base.py", line 329, in prepare_repositories
    url = self._prepare_content_sets(self.image.get('packages').get('content_sets'))
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/cekit/generator/base.py", line 377, in _prepare_content_sets
    compose = odcs.new_compose(repos, 'pulp', flags=flags)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/odcs/client/odcs.py", line 275, in new_compose
    r = self._post('composes/', request_data)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/odcs/client/odcs.py", line 202, in _post
    return self._make_request('post', resource_path, data)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/odcs/client/odcs.py", line 187, in _make_request
    r = request_method(resource_url, **request_data)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ce/cekit/3.3.1/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[REDACTED]', port=443): Max retries exceeded with url: /api/1/composes/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

Paste any logs you have, use CEKit verbose output: `cekit -v`.
```
(3.3.1) 🎩︎cekit --version
3.3.1
```

**Comment by jmtd** [comment]
This is a workaround:

```
cp /etc/ssl/certs/ca-bundle.crt /home/ce/cekit/3.4.0/lib/python2.7/site-packages/certifi/cacert.pem
```

**Comment by goldmann** [comment]
CEKit already warns about this in the output, it should be visible immediately at the top of the log . We cannot do anything more about it. See #577.

**Comment by goldmann** [comment]
This issue is related to the way you install and expect certificate bundles. For internal use, you should not have this package installed at all. By installing the certifi library you point to a different CA bundle which does not contain internal certificates.

Your workaround is fine, but this is for your environment. We do not have control over how people install CEKit and its dependencies and what are the expectations and the environment they run it in. I added already a warning to the output to make people aware from where the CA bundle is used so this makes debugging issues related to certificates much easier. We cannot guess whether the printed location is is correct or wrong.

**Comment by jmtd** [comment]
Hi @goldmann — thanks. I read the warning message exactly inside-out. I don't need or want certifi installed and I'm using pure virtualenvs anyway so I will strip it out. Thanks
