### ISSUE TITLE
problems with gitignore and adding artefacts

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#626]
**Describe the bug**
It is possible for cekit to attempt to add an artefact to the back-end dist-git repository and for this to fail because the artefact matches a line in gitignore that cekit put there much earlier.

**To reproduce**
I'm finding it tricky to guarantee a way of reproducing this but I can try to describe what is happening.

Different versions of the OpenJDK image's cct_module dependency define jolokia artefact in different ways depending on whether they pull cct_module before or after commit c3926fbc4480faa1dd11685b381fcb12403ef560

my private dist-git repo has a .gitignore containing (due to earlier cekit activity) the line
/jolokia-jvm-1.6.2.redhat-00002-agent.jar and also the binary in the root (not tracked by git) 
jolokia-jvm-1.6.2.redhat-00002-agent.jar

Also different versions of cekit have changed whether to put the artefacts in the root of the dist-git repo or the sub-directory "artefacts"

**Expected behavior**
There's a mismatch between what adds or removes gitignore lines and what adds or removes artefact binaries to the dist-git checkout. Ideally the two would be in sync.

A quick fix might be to adjust the "subprocess '['git', 'add', '--all'," call to also add "-f" or "--force"

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.
cekit 3.5.0

```
2019-10-02 11:09:01,428 cekit        DEBUG    Staging 'jolokia-jvm-1.6.2.redhat-00002-agent.jar'...
The following paths are ignored by one of your .gitignore files:
jolokia-jvm-1.6.2.redhat-00002-agent.jar
Use -f if you really want to add them.
fatal: no files added
Traceback (most recent call last):
  File "/home/ce/cekit/3.5.0/bin/cekit", line 11, in <module>
    load_entry_point('cekit==3.5.0', 'console_scripts', 'cekit')()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 175, in build_osbs
    run_build(ctx, 'osbs')
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 278, in run_build
    run_command(ctx, builder_impl)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 247, in run_command
    Cekit(params).run(clazz)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 337, in run
    command.execute()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/builder.py", line 66, in execute
    self.before_build()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/builders/osbs.py", line 90, in before_build
    self._sync_with_dist_git()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/builders/osbs.py", line 140, in _sync_with_dist_git
    self.dist_git.add(self.artifacts)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/builders/osbs.py", line 389, in add
    subprocess.check_call(["git", "add", "--all", obj])
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'add', '--all', 'jolokia-jvm-1.6.2.redhat-00002-agent.jar']' returned non-zero exit status 128


```

**Environment information:**
 - Operating system
 - CEKit version: Result of `cekit --version`

**Additional context**

**Comment by goldmann** [comment]
This is not strictly a bug. The problem are leftovers in the directory where you have checked out dist-git repository. If you remove the cache (this directory only), then it will work as expected.

**Comment by jmtd** [comment]
But cekit checked out the repo, right? and wrote the gitignore file, and put the artefact there (or took it away)…

**Comment by goldmann** [comment]
Correct, but the approach was changed in one version of CEKit. Previously we added things seletively, now we add everything from the directory. In case there are some leftovers from using previous version of CEKit, new approach will fail unless the cache is cleaned up. This is a one-time thing.

**Comment by goldmann** [comment]
I would like to close this ticket. I do not plan currently to work on this.
