### ISSUE TITLE
content_sets (or content_sets_file) cannot be overridden

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#628]
cekit 3.5.0

With [this image.yaml](https://github.com/jmtd/openjdk/blob/97a8819e36d861c8421acfd4000d763942003c16/image.yaml#L37), using `content_sets_file`, and [this override](https://github.com/jmtd/openjdk/blob/97a8819e36d861c8421acfd4000d763942003c16/rhel8-jdk8-overrides.yaml#L34), using embedded `content_sets`, cekit crashes as follows

```
…
2019-10-24 13:41:03,773 cekit        DEBUG    Reading descriptor from 'image.yaml' file...
Traceback (most recent call last):
  File "/home/ce/cekit/3.5.0/bin/cekit", line 11, in <module>
    load_entry_point('cekit==3.5.0', 'console_scripts', 'cekit')()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 175, in build_osbs
    run_build(ctx, 'osbs')
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 278, in run_build
    run_command(ctx, builder_impl)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 247, in run_command
    Cekit(params).run(clazz)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/cli.py", line 337, in run
    command.execute()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/builder.py", line 53, in execute
    self.before_generate()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/builder.py", line 97, in before_generate
    self.generator.init()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/generator/osbs.py", line 21, in init
    super(OSBSGenerator, self).init()
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/generator/base.py", line 112, in init
    self.image.apply_image_overrides(self._overrides)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/descriptor/image.py", line 248, in apply_image_overrides
    override.packages.content_sets, self.packages.content_sets)
  File "/home/ce/cekit/3.5.0/lib/python2.7/site-packages/cekit/descriptor/base.py", line 183, in _merge_descriptors
    if k2 in desc1.skip_merging:
AttributeError: 'dict' object has no attribute 'skip_merging'

```

**Comment by jmtd** [comment]
Actually it's not that simple it seems. Switching to an external `content_sets` file in the override ([here](https://github.com/jmtd/openjdk/blob/rm-centos/rhel8-jdk8-overrides.yaml#L32) and I get the same traceback. Likewise, only embeddeding the `content_sets` in `image.yaml` and then putting different embeds in the override, still breaks.

It seems impossible to override content sets.

**Comment by goldmann** [comment]
Interesting, I'll take a look at it!

**Comment by jmtd** [comment]
I've been thinking about this a little more. In the situation where the image.yaml uses (say) content_sets and the override uses content_sets_file (or the other way around), should that invalidate the content_sets key? It might be safer to check when both are being used and to bail out and say "don't do that"

**Comment by goldmann** [comment]
Internally, the `content_sets_file` key is converted into `content_sets` either case, so there shouldn't be any issue in handling both in overrides.

I'm working now on a fix for this and it looks like the merging approach could be pretty simplified. I would like to ask you to test the upcoming release once I have something ready. This would give me more confidence in the release. All tests are passing, but I would like to have more real-world use cases be tested as well.

**Comment by goldmann** [comment]
@jmtd Can I ask you to help me test this patch?

```bash
pip install -U https://github.com/goldmann/cekit/archive/gh-628-overriding-content-sets.zip
```

**Comment by goldmann** [comment]
@errantepiphany @luck3y Can I ask you to do the same with some fun images?
