### ISSUE TITLE
Multi-Stage Build artifact does not work properly

### ISSUE THREAD

**Issue by MarianZoll** [cekit/cekit#642]
Thanks for helping!

**Describe the bug**
When creating a multi-stage build (https://cekit.readthedocs.io/en/latest/handbook/multi-stage.html), the module artifacts cannot be copied to `tmp/artifacts` and the process stops without any meaningful explanation.

**To reproduce**
_To ensure reproducability, I added some snippets below_
1. Create a multi-stage `image.yaml`
2. Create a module that downloads an artifact (e.g.) ant in the first builder image
3. Run `cekit -v build docker`
4. Find the error logs as attached below

**Expected behavior**
The artifacts should be able to be copied to the temporary build image similar like in regular singe-stage builds. 

**Logs**
```
2019-11-21 11:07:43,418 cekit        DEBUG    Running version 3.6.0
2019-11-21 11:07:43,418 cekit        DEBUG    Configuring CEKit...
2019-11-21 11:07:43,419 cekit        DEBUG    Removing dirty directory: 'target/image/modules'
2019-11-21 11:07:43,419 cekit        DEBUG    Removing dirty directory: 'target/repo'
2019-11-21 11:07:43,421 cekit        WARNING  You are running CEKit on an unknown platform. External dependencies suggestions may not work!
2019-11-21 11:07:43,421 cekit        DEBUG    Checking CEKit core dependencies...
2019-11-21 11:07:43,421 cekit        DEBUG    Checking if 'git' dependency is provided...
2019-11-21 11:07:43,421 cekit        DEBUG    CEKit dependency 'git' provided via the '/usr/bin/git' executable.
2019-11-21 11:07:43,421 cekit        DEBUG    All dependencies provided!
2019-11-21 11:07:43,421 cekit        WARNING  The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2019-11-21 11:07:43,421 cekit        WARNING  Certificate Authority (CA) bundle in use: '/usr/local/lib/python3.7/site-packages/certifi/cacert.pem'
2019-11-21 11:07:43,496 cekit        INFO     Generating files for docker engine
2019-11-21 11:07:43,496 cekit        INFO     Initializing image descriptor...
2019-11-21 11:07:43,496 cekit        DEBUG    Checking CEKit generate dependencies...
2019-11-21 11:07:43,497 cekit        DEBUG    Checking if 'odcs-client' dependency is provided...
2019-11-21 11:07:43,497 cekit        DEBUG    Required CEKit library 'odcs-client' was found as a 'odcs' module!
2019-11-21 11:07:43,497 cekit        DEBUG    All dependencies provided!
2019-11-21 11:07:43,497 cekit        DEBUG    Removing old target directory
2019-11-21 11:07:43,497 cekit        DEBUG    Reading descriptor from 'image.yaml' file...
2019-11-21 11:07:43,504 cekit        INFO     Descriptor contains multiple elements, assuming multi-stage image
2019-11-21 11:07:43,504 cekit        INFO     Found 1 builder image(s) and one target image
2019-11-21 11:07:43,505 cekit        WARNING  No value found for 'name' in '{"path": "modules"}' artifact; using auto-generated value of 'modules'
2019-11-21 11:07:43,510 cekit        WARNING  No value found for 'name' in '{"image": "builder", "path": "/path/to/lib.jar"}' artifact; using auto-generated value of 'lib.jar'
2019-11-21 11:07:43,512 cekit        DEBUG    Downloading module repository: 'modules'
2019-11-21 11:07:43,512 cekit        INFO     Preparing resource 'modules'
2019-11-21 11:07:43,512 cekit        DEBUG    Copying repository from '/Users/marianzoll/GitHub_Projects/daimler-gtp/open-liberty-s2i/modules' to 'target/repo/modules'.
2019-11-21 11:07:43,517 cekit        DEBUG    Reading descriptor from '/Users/marianzoll/GitHub_Projects/daimler-gtp/open-liberty-s2i/target/repo/modules/ant/module.yaml' file...
2019-11-21 11:07:43,520 cekit        DEBUG    No value found for 'name' key in the execute section of the 'ant' module; using auto-generated value: 'ant/install.sh'
2019-11-21 11:07:43,520 cekit        DEBUG    Adding module 'ant', path: 'target/repo/modules/ant'
2019-11-21 11:07:43,521 cekit        DEBUG    Reading descriptor from '/Users/marianzoll/GitHub_Projects/daimler-gtp/open-liberty-s2i/target/repo/modules/maven/module.yaml' file...
2019-11-21 11:07:43,526 cekit        DEBUG    No value found for 'name' key in the execute section of the 'maven' module; using auto-generated value: 'maven/install.sh'
2019-11-21 11:07:43,526 cekit        DEBUG    Adding module 'maven', path: 'target/repo/modules/maven'
2019-11-21 11:07:43,527 cekit        DEBUG    Reading descriptor from '/Users/marianzoll/GitHub_Projects/daimler-gtp/open-liberty-s2i/target/repo/modules/ol-s2i/module.yaml' file...
2019-11-21 11:07:43,530 cekit        DEBUG    No value found for 'name' key in the execute section of the 'ol-s2i' module; using auto-generated value: 'ol-s2i/configure.sh'
2019-11-21 11:07:43,530 cekit        DEBUG    Adding module 'ol-s2i', path: 'target/repo/modules/ol-s2i'
2019-11-21 11:07:43,532 cekit        DEBUG    Copying module 'ant' required by 'websphere-liberty/websphere-liberty-s2i'.
2019-11-21 11:07:43,532 cekit        DEBUG    Copying module 'ant' to: 'target/image/modules/ant'
2019-11-21 11:07:43,538 cekit        DEBUG    Copying module 'ol-s2i' required by 'websphere-liberty/websphere-liberty-s2i'.
2019-11-21 11:07:43,539 cekit        DEBUG    Copying module 'ol-s2i' to: 'target/image/modules/ol-s2i'
2019-11-21 11:07:43,545 cekit        INFO     Handling artifacts...
2019-11-21 11:07:43,545 cekit        INFO     Preparing resource 'application'
2019-11-21 11:07:43,545 cekit        INFO     Preparing resource 'lib.jar'
2019-11-21 11:07:43,545 cekit        DEBUG    Artifacts handled
2019-11-21 11:07:43,552 cekit        INFO     Rendering Dockerfile...
2019-11-21 11:07:43,608 cekit        DEBUG    Dockerfile rendered
2019-11-21 11:07:43,608 cekit        DEBUG    Checking CEKit build dependencies...
2019-11-21 11:07:43,608 cekit        DEBUG    Checking if 'python-docker' dependency is provided...
2019-11-21 11:07:43,608 cekit        DEBUG    Required CEKit library 'python-docker' was found as a 'docker' module!
2019-11-21 11:07:43,609 cekit        DEBUG    Checking if 'docker-squash' dependency is provided...
2019-11-21 11:07:43,609 cekit        DEBUG    Required CEKit library 'docker-squash' was found as a 'docker_squash' module!
2019-11-21 11:07:43,609 cekit        DEBUG    All dependencies provided!
2019-11-21 11:07:43,609 cekit        INFO     Building container image using Docker...
2019-11-21 11:07:43,609 cekit        DEBUG    Building image with tags: 'websphere-liberty/websphere-liberty-s2i:19.0.0.9', 'websphere-liberty/websphere-liberty-s2i:latest'
2019-11-21 11:07:43,609 cekit        DEBUG    Preparing Docker client...
2019-11-21 11:07:43,619 cekit        DEBUG    Docker client ready and working
2019-11-21 11:07:43,636 cekit        DEBUG    {'Platform': {'Name': 'Docker Engine - Community'}, 'Components': [{'Name': 'Engine', 'Version': '19.03.4', 'Details': {'ApiVersion': '1.40', 'Arch': 'amd64', 'BuildTime': '2019-10-17T23:50:38.000000000+00:00', 'Experimental': 'false', 'GitCommit': '9013bf5', 'GoVersion': 'go1.12.10', 'KernelVersion': '4.9.184-linuxkit', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': 'v1.2.10', 'Details': {'GitCommit': 'b34a5c8af56e510852c35414db4c1f4fa6172339'}}, {'Name': 'runc', 'Version': '1.0.0-rc8+dev', 'Details': {'GitCommit': '3e425f80a8c931f88e6d94a8c831b9d5aa481657'}}, {'Name': 'docker-init', 'Version': '0.18.0', 'Details': {'GitCommit': 'fec3683'}}], 'Version': '19.03.4', 'ApiVersion': '1.40', 'MinAPIVersion': '1.12', 'GitCommit': '9013bf5', 'GoVersion': 'go1.12.10', 'Os': 'linux', 'Arch': 'amd64', 'KernelVersion': '4.9.184-linuxkit', 'BuildTime': '2019-10-17T23:50:38.000000000+00:00'}
2019-11-21 11:07:43,923 cekit        INFO     Docker: Step 1/21 : FROM registry.redhat.io/openjdk/openjdk-8-rhel8:latest AS builder
2019-11-21 11:07:43,923 cekit        INFO     Docker: 
2019-11-21 11:07:43,923 cekit        INFO     Docker: ---> c1d377a698e9
2019-11-21 11:07:43,924 cekit        INFO     Docker: Step 2/21 : USER root
2019-11-21 11:07:43,924 cekit        INFO     Docker: 
2019-11-21 11:07:43,925 cekit        INFO     Docker: ---> Using cache
2019-11-21 11:07:43,925 cekit        INFO     Docker: ---> 923fa32aed43
2019-11-21 11:07:43,925 cekit        INFO     Docker: Step 3/21 : COPY             ant.tar.gz             /tmp/artifacts/
2019-11-21 11:07:43,925 cekit        INFO     Docker: 
2019-11-21 11:07:43,926 cekit        ERROR    You can look inside the failed image by running 'docker run --rm -ti 923fa32aed43 bash'
2019-11-21 11:07:43,926 cekit        ERROR    ('Image build failed, see logs above.', CekitError("Image build failed: 'COPY failed: stat /var/lib/docker/tmp/docker-builder126787175/ant.tar.gz: no such file or directory'"))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 89, in _build_with_docker
    raise CekitError("Image build failed: '{}'".format(error_message))
cekit.errors.CekitError: Image build failed: 'COPY failed: stat /var/lib/docker/tmp/docker-builder126787175/ant.tar.gz: no such file or directory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cekit/cli.py", line 335, in run
    command.execute()
  File "/usr/local/lib/python3.7/site-packages/cekit/builder.py", line 67, in execute
    self.run()
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 242, in run
    image_id = self._build_with_docker(docker_client)
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 150, in _build_with_docker
    raise CekitError(msg, ex)
cekit.errors.CekitError: ('Image build failed, see logs above.', CekitError("Image build failed: 'COPY failed: stat /var/lib/docker/tmp/docker-builder126787175/ant.tar.gz: no such file or directory'"))
```

**Environment information:**
 - Operating system: macOS Catalina v10.15 
 - CEKit version: 3.6.0

**Additional context**
**image.yaml**
```
- name: builder
  version: 0.1
  from: registry.redhat.io/openjdk/openjdk-8-rhel8:latest
  description: "Websphere Liberty UBI image with javaee-8"

  modules:
    repositories:
      - path: modules
    # Install selected modules (in order)
    install:
      - name: ant
      - name: ol-s2i

- name: websphere-liberty/websphere-liberty-s2i
  version: 19.0.0.9
  from: ibmcom/websphere-liberty:19.0.0.9-kernel-ubi-min-amd64
  description: "Websphere Liberty UBI image with javaee-8"
  labels:
    - name: io.k8s.description
      value: "Websphere Liberty S2I Image"
    - name: io.k8s.display-name
      value: "Websphere Liberty S2I Builder"
    - name: io.openshift.tags
      value: "runner,builder,websphereliberty,javaee"
    - name: io.openshift.s2i.scripts-url
      value: image:///usr/local/s2i
    - name: io.s2i.scripts-url
      value: image:///usr/local/s2i
    - name: io.openshift.expose-services
      value: "9080/tcp:http, 9443/tcp:https"
    - name: io.openshift.s2i.destination
      value: "/tmp"

  envs:
    - name: STI_SCRIPTS_PATH
      value: "/usr/local/s2i"
    - name: WORKDIR
      value: "/usr/local/workdir"
    - name: S2I_DESTINATION
      value: "/tmp"
    - name: JAVA_HOME
      value: /opt/ibm/java/jre
    - name: PATH
      value: /opt/ibm/java/jre/bin:$PATH

  packages:
    manager: microdnf

  artifacts:
    - name: application
      image: builder
      path: /path/to/application/inside/the/builder/image.jar

    - image: builder
      path: /path/to/lib.jar

  run:
    user: 1001
    cmd:
      - "/opt/ibm/wlp/bin/server run defaultServer"
```
**module.yaml**
```
name: ant
version: 1.0
description: "Module used to install Ant"

# Defined artifacts that are used to build the image
artifacts:
  - name: ant.tar.gz
    url: https://www-eu.apache.org/dist//ant/binaries/apache-ant-1.10.7-bin.tar.gz
    sha512: 838ce70c7dbd2b53068ce17b169c0b3fbed5e0ab7be5c707f052418fb6a4a1620f2d4017ceca1379cd25edce3e46d70bb2b5de4e1c5c52e2e1275deec1228084

execute:
  - script: install.sh
```
**install.sh**
```
#!/bin/sh

set -e

    tar -C /usr/local -zxf /tmp/artifacts/ant.tar.gz \
      && ln -sf /usr/local/apache-ant-1.10.7/bin/ant /usr/local/bin/ant 
```

**Comment by goldmann** [comment]
Thanks for this report, I'm going to reproduce it locally. Hold on tight!

**Comment by goldmann** [comment]
I could reproduce it and I know what's going on, let's schedule it for a bugfix release.

**Comment by goldmann** [comment]
Would you be so kind to give this dirty fix a shot?

https://docs.cekit.io/en/latest/handbook/installation/instructions.html#other-systems

```
pip install -U https://github.com/goldmann/cekit/archive/gh-642-multi-stage-handling-artifacts.zip
```

**Comment by MarianZoll** [comment]
@goldmann 

Looks much better now! Thanks for the awesome support and the hotfix! 

Not sure if you want to close the ticket or if I should do it :)

**Comment by goldmann** [comment]
Thanks for the info (and report)!

Please leave it open, I need to work on tests. Will open a MR soon and reference this ticket.

**Comment by ryanemerson** [comment]
@goldmann I'm also hitting this issue. Any chance we can get  a `3.6.1` release with this fix soon?
