### ISSUE TITLE
Multi-stage run definitions are not executed in builder image

### ISSUE THREAD

**Issue by ryanemerson** [cekit/cekit#647]
**Describe the bug**
Any commands defined in the `run.command` section of a descriptor file are ignored when the builder image is executed. Modules are executed as expected, however defining commands in their `module.yaml` does not work.

**To reproduce**
`cekit build podman`
```yaml
- name: builder
  version: 1.0
  from: registry.access.redhat.com/ubi8/ubi-minimal:8.2-267
  run:
    cmd:
    - touch /opt/artifact
    user: 185

- name: runner
  version: 1.0
  from: registry.access.redhat.com/ubi8/ubi-minimal:8.2-267
  artifacts:
  - name: artifact
    image: builder
    path: /opt/artifact
  run:
    cmd:
    - cat /opt/artifact
    user: 185

```

**Expected behavior**
The cmd in the builder image should be executed before the "runner" image is processed.

**Logs**
```python
2020-05-11 16:46:38,303 cekit        DEBUG    Running version 3.7.dev0
2020-05-11 16:46:38,303 cekit        WARNING  You are running unreleased development version of CEKit, use it only at your own risk!
2020-05-11 16:46:38,303 cekit        DEBUG    Configuring CEKit...
2020-05-11 16:46:38,304 cekit        DEBUG    Removing dirty directory: 'target/repo'
2020-05-11 16:46:38,304 cekit        INFO     You are running on known platform: Fedora 30 (Workstation Edition)
2020-05-11 16:46:38,304 cekit        DEBUG    Checking CEKit core dependencies...
2020-05-11 16:46:38,304 cekit        DEBUG    Checking if 'git' dependency is provided...
2020-05-11 16:46:38,304 cekit        DEBUG    CEKit dependency 'git' provided via the '/usr/bin/git' executable.
2020-05-11 16:46:38,304 cekit        DEBUG    All dependencies provided!
2020-05-11 16:46:38,461 cekit        INFO     Generating files for podman engine
2020-05-11 16:46:38,462 cekit        INFO     Initializing image descriptor...
2020-05-11 16:46:38,463 cekit        DEBUG    Checking CEKit generate dependencies...
2020-05-11 16:46:38,463 cekit        DEBUG    Checking if 'odcs-client' dependency is provided...
2020-05-11 16:46:38,463 cekit        DEBUG    Required CEKit library 'odcs-client' was found as a 'odcs' module!
2020-05-11 16:46:38,463 cekit        DEBUG    Checking if 'brew' dependency is provided...
2020-05-11 16:46:38,463 cekit        DEBUG    All dependencies provided!
2020-05-11 16:46:38,463 cekit        DEBUG    Removing old target directory
2020-05-11 16:46:38,464 cekit        DEBUG    Reading descriptor from 'image.yaml' file...
2020-05-11 16:46:38,466 cekit        INFO     Descriptor contains multiple elements, assuming multi-stage image
2020-05-11 16:46:38,466 cekit        INFO     Found 1 builder image(s) and one target image
2020-05-11 16:46:38,478 cekit        INFO     Handling artifacts...
2020-05-11 16:46:38,478 cekit        INFO     Preparing resource 'artifact'
2020-05-11 16:46:38,479 cekit        DEBUG    Artifacts handled
2020-05-11 16:46:38,482 cekit        INFO     Rendering Dockerfile...
2020-05-11 16:46:38,535 cekit        DEBUG    Dockerfile rendered
2020-05-11 16:46:38,535 cekit        DEBUG    Checking CEKit build dependencies...
2020-05-11 16:46:38,535 cekit        DEBUG    Checking if 'podman' dependency is provided...
2020-05-11 16:46:38,535 cekit        DEBUG    CEKit dependency 'podman' provided via the '/usr/bin/podman' executable.
2020-05-11 16:46:38,535 cekit        DEBUG    All dependencies provided!
2020-05-11 16:46:38,535 cekit        DEBUG    Building image with tags: 'runner:1.0', 'runner:latest'
2020-05-11 16:46:38,535 cekit        INFO     Building container image...
2020-05-11 16:46:38,535 cekit        DEBUG    Running Podman build: '/usr/bin/podman build --squash -t runner:1.0 -t runner:latest target/image'
STEP 1: FROM registry.access.redhat.com/ubi8/ubi-minimal:8.2-267 AS builder
STEP 2: USER root
STEP 3: ENV             JBOSS_IMAGE_NAME="runner"             JBOSS_IMAGE_VERSION="1.0" 
STEP 4: LABEL             name="runner"              version="1.0" 
STEP 5: FROM registry.access.redhat.com/ubi8/ubi-minimal:8.2-267
STEP 6: USER root
STEP 7: COPY --from=builder /opt/artifact /tmp/artifacts/artifact
Error: error building at STEP "COPY --from=builder /opt/artifact /tmp/artifacts/artifact": no files found matching "/home/remerson/.local/share/containers/storage/overlay/733f28b204d0eb5a7469b06d39399e8f1ea894f1acfc31487cca3e9434e771fa/merged/opt/artifact": no such file or directory
2020-05-11 16:46:39,004 cekit        ERROR    Image build failed, see logs above.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/podman.py", line 55, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/podman', 'build', '--squash', '-t', 'runner:1.0', '-t', 'runner:latest', 'target/image']' returned non-zero exit status 125.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cekit/cli.py", line 335, in run
    command.execute()
  File "/usr/local/lib/python3.7/site-packages/cekit/builder.py", line 67, in execute
    self.run()
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/podman.py", line 59, in run
    raise CekitError("Image build failed, see logs above.")
cekit.errors.CekitError: Image build failed, see logs above.

```

**Environment information:**
 - Operating system: Fedora 30
 - CEKit version: 3.6.0 and with https://github.com/goldmann/cekit/commit/abf50fdf88187fba1b6779fe7f2919bc551312f2 applied

**Comment by ryanemerson** [comment]
That makes sense, thanks for clarifying.

> If you think documentation about the `run` section needs to be extended, let me know what would be the best way to rephrase it. Current status: https://docs.cekit.io/en/latest/descriptor/image.html#run

In the image descriptor documentation it could be helpful to indicate whether a key is applicable to intermediary images and/or final images.

**Comment by goldmann** [comment]
> In the image descriptor documentation it could be helpful to indicate whether a key is applicable to intermediary images and/or final images.

I looked briefly at the descriptor documentation and I found that following properties are not really useful for builder images:

* ports
* volumes
* run 
* help
* osbs

I think I'll just add a note to the multi-stage builds documentation, here: https://docs.cekit.io/en/latest/handbook/multi-stage.html
