### ISSUE TITLE
Multi stage builds does not work properly on osbs

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#649]
**Describe the bug**
There is a issue when building release images with osbs and multistage builds
this is the image file: https://github.com/kiegroup/kie-cloud-operator/blob/master/image.yaml
Copying content here as we'll probably revert it back to the normal build.

```
- schema_version: 1
  name: "builder"
  description: "Golang builder image"
  version: "7.8.1"
  from: "rhel8-go-toolset:1.12.8-released"
  modules:
    repositories:
      - name: builder
        path: modules/builder
    install:
      - name: builder
  osbs:      
    configuration:
      container:
        platforms:
          only:
            - x86_64

- schema_version: 1
  name: "rhpam-7/rhpam-rhel8-operator"
  description: "Red Hat Business Automation Operator"
  version: "7.8.1"
  from: "ubi8-minimal:8-released"
  labels:
    - name: "maintainer"
      value: "bsig-cloud@redhat.com"
    - name: "com.redhat.component"
      value: "rhpam-7-rhel8-operator-container"
    - name: "io.k8s.description"
      value: "Operator for deploying RHPAM & RHDM"
    - name: "io.k8s.display-name"
      value: "Red Hat Business Automation Operator"
    - name: "io.openshift.tags"
      value: "rhpam,rhdm,operator"
  modules:
    repositories:
      - name: runtime
        path: modules/runtime
    install:
      - name: runtime
  osbs:
    configuration:
      container:
        go:
          modules:
          - module: github.com/kiegroup/kie-cloud-operator
            archive: kie-cloud-operator.tar.gz
        platforms:
          only:
            - x86_64
    extra_dir: osbs-extra
    repository:
      name: containers/rhpam-7-operator
      branch: rhba-7-rhel-8
  run:
    user: "1001"
```

This issue happens:
```
2020-07-01 10:09:42,419 cekit        DEBUG    Executing '['/usr/bin/rhpkg', 'new-sources', 'kie-cloud-operator.tar.gz', 'kie-cloud-operator', 'console-cr-form']'
2020-07-01 10:09:42,709 cekit        ERROR    Cannot run '['/usr/bin/rhpkg', 'new-sources', 'kie-cloud-operator.tar.gz', 'kie-cloud-operator', 'console-cr-form']', output: 'b'Could not execute new_sources: Path does not exist or is not a file: kie-cloud-operator\n''
2020-07-01 10:09:42,710 cekit        ERROR    Cannot update sources.
```
This issue is triggered by the artifacts listed in this module:
https://github.com/kiegroup/kie-cloud-operator/blob/release-v7.8.x/modules/runtime/module.yaml#L6 :+1: 
```
schema_version: 1

name: runtime
version: "1.0"

artifacts:
  - name: kie-cloud-operator
    image: builder
    path: /usr/local/bin/kie-cloud-operator
  - name: console-cr-form
    image: builder
    path: /usr/local/bin/console-cr-form

execute:
  - script: install
```

these artifacts will be provided within the first stage build.....
These files should come from the first step  which hasn't occurred yet., from builder image,  so those artifacts don't exist and can't be cached.
but apparently using osbs the files needs to be updated to osbs before the build itself.

**To reproduce**
Try to build a multistage release image on osbs.
Can be done with  this script:

```bash
#!/bin/sh
kinit
git clone -b 7.8.0 https://github.com/kiegroup/kie-cloud-operator
cd kie-cloud-operator

TAR=modules/builder/kie-cloud-operator.tar.gz
URL=https://github.com/kiegroup/kie-cloud-operator/archive/7.8.0.tar.gz
wget -q ${URL} -O ${TAR}
cekit --verbose --redhat build osbs  --release
```

**Expected behavior**
Successful build.

**Logs**
> cekit --verbose --redhat build osbs  --release

```
2020-07-02 14:42:54,017 cekit        INFO     Updating lookaside cache...
2020-07-02 14:42:54,017 cekit        DEBUG    Executing '['/usr/bin/rhpkg', 'new-sources', 'kie-cloud-operator', 'console-cr-form']'
2020-07-02 14:42:54,307 cekit        ERROR    Cannot run '['/usr/bin/rhpkg', 'new-sources', 'kie-cloud-operator', 'console-cr-form']', output: 'b'Could not execute new_sources: Path does not exist or is not a file: kie-cloud-operator\n''
2020-07-02 14:42:54,307 cekit        ERROR    Cannot update sources.
Traceback (most recent call last):
  File "/home/anstephe/ant/cekit360/lib/python3.6/site-packages/cekit/builders/osbs.py", line 224, in update_lookaside_cache
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/rhpkg', 'new-sources', 'kie-cloud-operator', 'console-cr-form']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anstephe/ant/cekit360/lib/python3.6/site-packages/cekit/cli.py", line 335, in run
    command.execute()
  File "/home/anstephe/ant/cekit360/lib/python3.6/site-packages/cekit/builder.py", line 66, in execute
    self.before_build()
  File "/home/anstephe/ant/cekit360/lib/python3.6/site-packages/cekit/builders/osbs.py", line 90, in before_build
    self._sync_with_dist_git()
  File "/home/anstephe/ant/cekit360/lib/python3.6/site-packages/cekit/builders/osbs.py", line 141, in _sync_with_dist_git
    self.update_lookaside_cache()
  File "/home/anstephe/ant/cekit360/lib/python3.6/site-packages/cekit/builders/osbs.py", line 227, in update_lookaside_cache
    raise CekitError("Cannot update sources.")
cekit.errors.CekitError: Cannot update sources.
```

**Environment information:**
 - Fedora 31.
 - CEKit version: 3.6.0

**Comment by tchughesiv** [comment]
links to cekit files by commit - 
https://github.com/kiegroup/kie-cloud-operator/blob/a1ec992547664beca890a9b4b90b8d49eb5c7f56/image.yaml
https://github.com/kiegroup/kie-cloud-operator/blob/a1ec992547664beca890a9b4b90b8d49eb5c7f56/modules/runtime/module.yaml

**Comment by ryanemerson** [comment]
The Infinispan team is also running into this issue.

**Comment by goldmann** [comment]
@spolti @ryanemerson @tchughesiv Hey, thanks for reporting this!

Can we work out some minimal reproducer for it? Provided files are not complete at this point and, as long as I tried to adjust them, I'm not sure if this is the expected behavior. Maybe we could extend the https://github.com/cekit/cekit/tree/develop/tests/images/multi-stage example and add relevant bits that would help me understand the issue? Would someone be willing to work with me on this?

I have some idea where the problem could be, but I want to understand better the workflow, because maybe it's about writing guidelines (as well).

**Comment by goldmann** [comment]
I think I have crafted something that could be useful for reproducing this issue.

**Comment by goldmann** [comment]
I've opened a WIP PR to potentially handle this. The issue I found is that artifacts from builder images were ignored and thus the sync with dist-git was partially broken. PR sill requires work on tests and so on, but feel free to try it out with your use cases and reply with your findings.

To install you can use these instructions: https://docs.cekit.io/en/latest/handbook/installation/instructions.html#other-systems. Replace the `pip install` command with:

```
pip install -U https://github.com/goldmann/cekit/archive/gh-649-multi-stage-osbs.zip
```

**Comment by goldmann** [comment]
Here are full instructions on how to test it:

```bash
# Prepare virtual environment
virtualenv ~/cekit
source ~/cekit/bin/activate

# Install CEKit
# Execute the same command to upgrade to latest version
pip install -U https://github.com/goldmann/cekit/archive/gh-649-multi-stage-osbs.zip

# Now you are able to run CEKit
cekit --help
```

Once you are done, run `deactivate` to use system-wide installation.

**Comment by ryanemerson** [comment]
@goldmann The fix seems to work for our use-case. I didn't push the changes, but this is further than we got last time:

```
2020-07-23 11:40:19,494 cekit        WARNING  You are running unreleased development version of CEKit, use it only at your own risk!
2020-07-23 11:40:19,496 cekit        INFO     You are running on known platform: Fedora 32 (Workstation Edition)
2020-07-23 11:40:19,558 cekit        INFO     Generating files for OSBS engine
2020-07-23 11:40:19,559 cekit        INFO     Initializing image descriptor...
2020-07-23 11:40:19,580 cekit        INFO     Descriptor contains multiple elements, assuming multi-stage image
2020-07-23 11:40:19,580 cekit        INFO     Found 1 builder image(s) and one target image
2020-07-23 11:40:19,582 cekit        WARNING  No value found for 'name' in '{"path": "modules"}' artifact; using auto-generated value of 'modules'
2020-07-23 11:40:19,587 cekit        WARNING  No value found for 'name' in '{"path": "modules"}' artifact; using auto-generated value of 'modules'
2020-07-23 11:40:19,589 cekit        WARNING  Module repository 'modules' already added, please check your image configuration, skipping module repository 'modules'
2020-07-23 11:40:19,589 cekit        INFO     Preparing resource 'modules'
2020-07-23 11:40:19,602 cekit        WARNING  Module's 'org.infinispan.distribution' version 'jvm' does not follow PEP 440 versioning scheme (https://www.python.org/dev/peps/pep-0440), we suggest follow this versioning scheme in modules
2020-07-23 11:40:19,611 cekit        WARNING  Module's 'org.infinispan.dependencies' version 'datagrid' does not follow PEP 440 versioning scheme (https://www.python.org/dev/peps/pep-0440), we suggest follow this versioning scheme in modules
2020-07-23 11:40:19,616 cekit        WARNING  Module's 'org.infinispan.dependencies.jdk' version 'openjdk' does not follow PEP 440 versioning scheme (https://www.python.org/dev/peps/pep-0440), we suggest follow this versioning scheme in modules
2020-07-23 11:40:19,642 cekit        INFO     Handling artifacts...
2020-07-23 11:40:19,643 cekit        INFO     Preparing artifact config-generator
2020-07-23 11:40:19,643 cekit        INFO     Preparing resource 'config-generator'
2020-07-23 11:40:19,643 cekit        INFO     Preparing artifact server
2020-07-23 11:40:28,201 cekit        INFO     Preparing artifact config-generator-src
2020-07-23 11:40:28,202 cekit        INFO     Preparing resource 'config-generator-src'
2020-07-23 11:40:29,401 cekit        WARNING  The image has ContentSets repositories specified, all other repositories are removed!
2020-07-23 11:40:29,438 cekit        INFO     Rendering Dockerfile...
2020-07-23 11:40:29,498 cekit        INFO     Pulling latest changes in repo containers/datagrid-8...
Could not chdir to home directory /home/remote/remerson: No such file or directory
Already on 'datagrid-8-rhel-8'
Your branch is up to date with 'origin/datagrid-8-rhel-8'.
HEAD is now at f388ca1 8.1.0.GA.1
2020-07-23 11:40:33,167 cekit        INFO     Removing old 'repos' directory
2020-07-23 11:40:33,168 cekit        INFO     Removing old 'modules' directory
2020-07-23 11:40:33,170 cekit        INFO     Removing old 'fetch-artifacts-url.yaml' file
rm 'fetch-artifacts-url.yaml'
2020-07-23 11:40:33,239 cekit        INFO     Updating lookaside cache...
2020-07-23 11:40:35,237 cekit        INFO     Update finished.
2020-07-23 11:40:35,240 cekit        INFO     Committing with message: 'Sync with infinispan-images, commit 38ccd93853c36c7148492fb037f337e1bc34ae73'
On branch datagrid-8-rhel-8
Your branch is ahead of 'origin/datagrid-8-rhel-8' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Are you ok with the changes? [y/N]: y
Do you want to push the commit? [y/N]: n
2020-07-23 11:41:33,342 cekit        INFO     Changes are not pushed, exiting

```

**Comment by goldmann** [comment]
Does it mean that the commit contains everything that was expected there? Would it be possible to run a scratch build to confirm it?

**Comment by goldmann** [comment]
I've got confirmation offline that such builds can be built properly using latest codebase.
