### ISSUE TITLE
using OSBS `extra_dir` causes FileExistsError

### ISSUE THREAD

**Issue by tchughesiv** [cekit/cekit#681]
**Describe the bug**
Using `osbs.extra_dir` errors out if a subdirectory already exists within the osbs repo. This means `extra_dir` can only be used one time for a given directory since all subsequent runs will have issues.

**To reproduce**
From the root of https://github.com/kiegroup/kie-cloud-operator, run `make bundle-scratch`.
The configuration of note is here -
https://github.com/kiegroup/kie-cloud-operator/blob/7545728aba62b8c98f564dcc680d60ce8a3e3e44/hack/go-build-bundle.sh#L59-L61
The dir we're adding is here -
https://github.com/kiegroup/kie-cloud-operator/tree/7545728aba62b8c98f564dcc680d60ce8a3e3e44/deploy/olm-catalog/prod/7.11.0-1

**Expected behavior**
If the specified `extra_dir` has subdirectories that already exist in the osbs repo, cekit should apply deltas.

**Logs**
```
2021-03-02 10:47:08,656 osbs.py:145        DEBUG Copying files to dist-git '/root/.cekit/osbs/containers/rhpam-operator-bundle' directory
2021-03-02 10:47:08,656 tools.py:159        DEBUG Copying 'target/image/manifests' to '/root/.cekit/osbs/containers/rhpam-operator-bundle/manifests'...
Traceback (most recent call last):
  File "/root/osbs/bin/cekit", line 8, in <module>
    sys.exit(cli())
  File "/root/osbs/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/osbs/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/osbs/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/osbs/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/osbs/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/osbs/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/osbs/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/osbs/lib/python3.6/site-packages/cekit/cli.py", line 173, in build_osbs
    run_build(ctx, 'osbs')
  File "/root/osbs/lib/python3.6/site-packages/cekit/cli.py", line 276, in run_build
    run_command(ctx, builder_impl)
  File "/root/osbs/lib/python3.6/site-packages/cekit/cli.py", line 245, in run_command
    Cekit(params).run(clazz)
  File "/root/osbs/lib/python3.6/site-packages/cekit/cli.py", line 335, in run
    command.execute()
  File "/root/osbs/lib/python3.6/site-packages/cekit/builder.py", line 66, in execute
    self.before_build()
  File "/root/osbs/lib/python3.6/site-packages/cekit/builders/osbs.py", line 89, in before_build
    self._copy_to_dist_git()
  File "/root/osbs/lib/python3.6/site-packages/cekit/builders/osbs.py", line 146, in _copy_to_dist_git
    copy_recursively(os.path.join(self.target, 'image'), self.dist_git_dir)
  File "/root/osbs/lib/python3.6/site-packages/cekit/tools.py", line 167, in copy_recursively
    shutil.copytree(src, dst, symlinks=True)
  File "/root/osbs/lib64/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/root/osbs/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.cekit/osbs/containers/rhpam-operator-bundle/manifests'
```

**Environment information:**
 - RHEL 8.2
 - CEKit version: 3.8.0
 - go 1.13.x

**Comment by rnc** [comment]
Thanks for the comprehensive report and test case.

**Comment by rnc** [comment]
I think this is because `shutil.copytree` will default to throwing an exception if a recursively copied directory already exists.
