### ISSUE TITLE
Container tests hanging in `container.execute(sh -c 'echo $USER',False)`

### ISSUE THREAD

**Issue by ricardozanini** [cekit/cekit#903]
**Describe the bug**
Not sure if it's a bug or an env related. Locally, I couldn't reproduce it. On our Jenkins CI, we have a very simple BDD test:

```feature
Feature: Common tests for Kogito images

  Scenario: Verify if Kogito user is correctly configured
    When container is started with command sh
    Then run sh -c 'echo $USER' in container and check its output for kogito
     And run sh -c 'echo $HOME' in container and check its output for /home/kogito
     And run sh -c 'id' in container and check its output for uid=1001(kogito) gid=0(root) groups=0(root),1001(kogito)
```

**To reproduce**
The image descriptor looks like this:

```yaml
name: "quay.io/kiegroup/kogito-base-builder"
version: "999-SNAPSHOT"
from: "registry.access.redhat.com/ubi8/ubi-minimal:latest"

modules:
  repositories:
    - path: modules
  install:
    - name: org.kie.kogito.image.dependencies
    - name: org.kie.kogito.system.user
    - name: org.kie.kogito.logging
    - name: org.kie.kogito.launch.scripts
    - name: org.kie.kogito.openjdk
      version: "17"
    - name: org.kie.kogito.dynamic.resources
    - name: org.kie.kogito.maven
      version: "3.9.3"
    - name: org.kie.kogito.maven.common
    - name: org.kie.kogito.project.versions
    - name: org.kie.kogito.security.custom.truststores

run:
  workdir: "/home/kogito"
  user: 1001
```

It's not complex at all.

**Expected behavior**

**Logs**

Then when running this test, we can see that's hanging on:

```log
 Scenario: Verify if Kogito user is correctly configured                                                             # features/image/common.feature:15
    When container is started with command sh                                                                         # steps/container_steps.py:106
2024-03-14 17:34:44,579 container.py:238        DEBUG Creating container from image 'quay.io/kiegroup/kogito-base-builder:999-SNAPSHOT'...
2024-03-14 17:34:44,579 container.py:254        DEBUG Creating docker container with arguments and image:  quay.io/kiegroup/kogito-base-builder:999-SNAPSHOT
2024-03-14 17:34:45,594 container.py:145        DEBUG Starting container 'fc87045ba2ffb0663fe27c072879d11fda30bcd69ae0c6d42499091b4ae19df2'...
2024-03-14 17:34:46,602 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:46,602 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:47,736 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:47,736 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:48,868 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:48,869 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:50,011 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:50,011 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:51,169 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:51,170 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:52,313 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:52,314 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:53,461 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:53,462 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:54,610 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:54,611 container.py:152        DEBUG container.execute(ps -C java,False)
2024-03-14 17:34:55,756 container_steps.py:317        DEBUG Running command ps -C java in container
2024-03-14 17:34:55,756 container.py:152        DEBUG container.execute(ps -C java,False)
    Then run sh -c 'echo $USER' in container and check its output for kogito                                          # steps/container_steps.py:305
2024-03-14 17:34:56,897 container_steps.py:325        DEBUG Running command sh -c 'echo $USER' in container with timeout 80
2024-03-14 17:34:56,898 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:34:58,017 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:34:59,170 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:00,318 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:01,451 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:02,587 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:03,727 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:04,871 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:06,011 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:07,146 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:08,279 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:09,430 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:10,563 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:11,696 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:12,847 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:13,982 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:15,115 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:16,256 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:17,400 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:18,549 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:19,690 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:20,833 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:21,974 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:23,106 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:24,249 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:25,386 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:26,518 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:27,652 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:28,787 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:29,920 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:31,069 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:32,212 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:33,329 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:34,471 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:35,603 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:36,729 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:37,855 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:38,981 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:40,106 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:41,241 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:42,381 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:43,516 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:44,643 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:45,767 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:46,916 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:48,060 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:49,201 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:50,334 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:51,476 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:52,612 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:53,744 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:54,878 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:56,002 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:57,137 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:58,281 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:35:59,404 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:00,536 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:01,672 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:02,805 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:03,922 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:05,048 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:06,198 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:07,331 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:08,465 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:09,599 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:10,749 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:11,892 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:13,025 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:14,177 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:15,308 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
2024-03-14 17:36:16,435 container.py:152        DEBUG container.execute(sh -c 'echo $USER',False)
      Traceback (most recent call last):
        File "/home/nonrootuser/.local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/nonrootuser/.local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "steps/container_steps.py", line 337, in run_command_expect_message
          raise Exception("Phrase '%s' was not found in the output of running the '%s' command" % (output_phrase, cmd),
      Exception: ("Phrase 'kogito' was not found in the output of running the 'sh -c 'echo $USER'' command", None, ExecException("container.execute: timeout reading from exec (command 'sh -c 'echo $USER'')"))
2024-03-14 17:36:17,589 container.py:134        DEBUG Removing container 'fc87045ba2ffb0663fe27c072879d11fda30bcd69ae0c6d42499091b4ae19df2'
2024-03-14 17:36:18,701 container.py:101        INFO  Removing container 'fc87045ba2ffb0663fe27c072879d11fda30bcd69ae0c6d42499091b4ae19df2', 1 try...
2024-03-14 17:36:19,010 container.py:104        INFO  Container 'fc87045ba2ffb0663fe27c072879d11fda30bcd69ae0c6d42499091b4ae19df2' removed
    And run sh -c 'echo $HOME' in container and check its output for /home/kogito                                     # None
    And run sh -c 'id' in container and check its output for uid=1001(kogito) gid=0(root) groups=0(root),1001(kogito) # None
```

**Environment information:**
 - Operating system Ubuntu
 - CEKit version: Result of `cekit --version` 4.8.0

**Additional context**
This is more of a call for help identifying what the problem could be.

**Comment by jmtd** [comment]
Did this just break recently? Could it be related to https://github.com/cekit/behave-test-steps/commit/bf4044075c41ac66ffcc23a7450938237f4bdeb2 ?

**Comment by jmtd** [comment]
It's worth noting the log output shows that `container.execute` returns "successfully" to the caller, and it's the parent procedure [run_command_expect_message](https://github.com/cekit/behave-test-steps/blob/v1/steps/container_steps.py#L308) that is throwing the exception. I wonder what the behaviour was prior to https://github.com/cekit/behave-test-steps/commit/bf4044075c41ac66ffcc23a7450938237f4bdeb2 ?

**Comment by ricardozanini** [comment]
> Did this just break recently? Could it be related to [cekit/behave-test-steps@bf40440](https://github.com/cekit/behave-test-steps/commit/bf4044075c41ac66ffcc23a7450938237f4bdeb2) ? You could fork that repo, and set the fork's `v2` branch to the commit just prior to that, and then in the test run, use `--steps-uri <your fork>` to verify.

Yes! It was working before and I noticed this behavior last week in the opened PR linked to this issue. I'll take a look at the code you pointed, thanks!

**Comment by ricardozanini** [comment]
@jmtd how the behave-test-steps are executed? Isn't this change only for the newer Cekit versions? We are using 4.8.0 in the CI.

**Comment by ricardozanini** [comment]
I see now:

```
  --steps-url TEXT   Behave steps library.  [default: https://github.com/cekit/behave-test-
                     steps.git]
```

**Comment by jmtd** [comment]
Cekit clones (in almost all cases) `behave-test-steps` and switches to branch `v2`, so, even if cekit itself is not updated, if `behave-test-steps` is, the situation changes. I think we should in-source `behave-test-steps` to cekit eventually, which would stop this happening (cc @rnc ). That might be a long way off though

**Comment by ricardozanini** [comment]
@jmtd I'm upgrading the Cekit on my environment. I tested locally with my v2 fork and worked.

**Comment by jmtd** [comment]
> @jmtd I'm upgrading Cekit on our CI environment. I tested locally with my v2 fork and worked.

To be clear: your fork of `behave-test-steps` has a v1 branch pointing at [40a940fc345dd6bbe100b87033cb2417b7afe693](https://github.com/cekit/behave-test-steps/commit/40a940fc345dd6bbe100b87033cb2417b7afe693) (which is the commit prior to [bf4044075c41ac66ffcc23a7450938237f4bdeb2](https://github.com/cekit/behave-test-steps/commit/bf4044075c41ac66ffcc23a7450938237f4bdeb2), mine, which we suspect is the problem), and you've altered the CI where the problem was occurring to reference your fork, and the problem has gone away?

**Comment by ricardozanini** [comment]
Hey @jmtd sorry for not being clear. Yes, that's what I've done: https://github.com/ricardozanini/behave-test-steps/tree/v2

And yes, it worked: https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fpullrequest%2Fkogito-images.build-and-test/detail/kogito-images.build-and-test/127/pipeline

I'm investigating the test that failed.

**Comment by jmtd** [comment]
It's possible that this will fix it : https://github.com/cekit/behave-test-steps/pull/60

you can test this by using --steps-url https://github.com/jmtd/behave-test-steps  , I've set that v1 branch to match the PR branch. would you mind checking that please?

**Comment by jmtd** [comment]
BTW to reiterate, I confused the issue earlier rby mentioning `v2`. Cekit uses the `v1` branch: it actually chooses branch  based on  the `schema_version` in your image YAML. So `v2` is a red herring here.

**Comment by ricardozanini** [comment]
@jmtd I've updated my PR to use your fork now: https://github.com/apache/incubator-kie-kogito-images/pull/1750/commits/bd71ba3af320b73e4d135e89d8ffdf8e7838caf5

We can follow the tests here: https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fpullrequest%2Fkogito-images-pr/detail/PR-1750/9/

**Comment by rnc** [comment]
I think this should be resolved now?

**Comment by jmtd** [comment]
> I think this should be resolved now?

I was hoping so, but https://ci-builds.apache.org/blue/organizations/jenkins/KIE%2Fkogito%2Fmain%2Fpullrequest%2Fkogito-images-pr/detail/PR-1750/9/ says "Tests on images seems to have failed: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images.build-and-test/128/". I'm taking a look at that second URI now, but we might need @ricardozanini to parse what happened.

**Comment by ricardozanini** [comment]
@jmtd @rnc it's working, can we merge the fix?

**Comment by ricardozanini** [comment]
@jmtd the error is:

```
Error
Message 'started in' was not found in the logs
Stacktrace
Failing step: And container log should contain started in ... failed in 30.564s
Location: features/image/jobs-service/kogito-jobs-service-ephemeral.feature:21
Traceback (most recent call last):
  File "/home/nonrootuser/.local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/home/nonrootuser/.local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps/container_steps.py", line 34, in log_contains_msg
    raise Exception("Message '%s' was not found in the logs" % message)
Exception: Message 'started in' was not found in the logs
Captured logging:
INFO:cekit:Message '-Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/ephemeral/quarkus-app/quarkus-run.jar' was found in the logs
Standard Output
@scenario.begin
  Scenario: Verify if the debug is correctly enabled with the ephemeral jar
    When container is started with env ... passed in 14.628s
      | variable     | value |
      | SCRIPT_DEBUG | true  |
    Then container log should contain -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/ephemeral/quarkus-app/quarkus-run.jar ... passed in 0.019s
    And container log should contain started in ... failed in 30.564s
    And container log should not contain Application failed to start ... skipped in 0.000s
@scenario.end
--------------------------------------------------------------------------------
```

Which we were facing before already when migrated to this platform. The command just hangs and timeouts. I don't know why and we didn't have the time to debug yet.

Might be related to cekit-behave, but I can't say for sure.

**Comment by ricardozanini** [comment]
More logs:

```
o: Verify if the debug is correctly enabled with the ephemeral jar                                                                            # features/image/jobs-service/kogito-jobs-service-ephemeral.feature:16
    When container is started with env                                                                                                                 # steps/container_steps.py:72
      | variable     | value |
      | SCRIPT_DEBUG | true  |
[37m2024-03-26 11:03:12,647 container.py:238        DEBUG Creating container from image 'quay.io/kiegroup/kogito-jobs-service-ephemeral:999-SNAPSHOT'...[0m
[37m2024-03-26 11:03:12,647 container.py:254        DEBUG Creating docker container with arguments and image: -e SCRIPT_DEBUG=true quay.io/kiegroup/kogito-jobs-service-ephemeral:999-SNAPSHOT[0m
[37m2024-03-26 11:03:14,292 container.py:95         DEBUG Starting container 'f004cde8d7960b17cc337e865046ada133af3e885b42228f0427ab7813500f4d'...[0m
[37m2024-03-26 11:03:15,865 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:15,865 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:17,223 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:17,224 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:18,632 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:18,633 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:19,923 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:19,923 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:21,414 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:21,415 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:22,691 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:22,691 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:24,123 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:24,123 container.py:152        DEBUG container.execute(ps -C java,False)[0m
[37m2024-03-26 11:03:25,469 container_steps.py:317        DEBUG Running command ps -C java in container[0m
[37m2024-03-26 11:03:25,470 container.py:152        DEBUG container.execute(ps -C java,False)[0m
    Then container log should contain -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/ephemeral/quarkus-app/quarkus-run.jar # steps/container_steps.py:31
[32m2024-03-26 11:03:27,294 container_steps.py:215        INFO  Message '-Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/ephemeral/quarkus-app/quarkus-run.jar' was found in the logs[0m
    And container log should contain started in                                                                                                        # steps/container_steps.py:31
      Traceback (most recent call last):
        File "/home/nonrootuser/.local/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/nonrootuser/.local/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "steps/container_steps.py", line 34, in log_contains_msg
          raise Exception("Message '%s' was not found in the logs" % message)
      Exception: Message 'started in' was not found in the logs
      
      Captured logging:
      INFO:cekit:Message '-Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/ephemeral/quarkus-app/quarkus-run.jar' was found in the logs

[37m2024-03-26 11:03:57,877 container.py:134        DEBUG Removing container 'f004cde8d7960b17cc337e865046ada133af3e885b42228f0427ab7813500f4d'[0m
[32m2024-03-26 11:04:00,538 container.py:101        INFO  Removing container 'f004cde8d7960b17cc337e865046ada133af3e885b42228f0427ab7813500f4d', 1 try...[0m
[32m2024-03-26 11:04:01,291 container.py:104        INFO  Container 'f004cde8d7960b17cc337e865046ada133af3e885b42228f0427ab7813500f4d' removed[0m
    And container log should not contain Application failed to start                                                                                   # None

[31m2024-03-26 11:04:01,297 cli.py:542        ERROR Test execution failed, please consult output above[0m
Traceback (most recent call last):
  File "/home/nonrootuser/.local/lib/python3.11/site-packages/cekit/cli.py", line 528, in run
    command.execute()
  File "/home/nonrootuser/.local/lib/python3.11/site-packages/cekit/builder.py", line 32, in execute
    self.run()
  File "/home/nonrootuser/.local/lib/python3.11/site-packages/cekit/test/behave_tester.py", line 74, in run
    self.test_runner.run(
  File "/home/nonrootuser/.local/lib/python3.11/site-packages/cekit/test/behave_runner.py", line 83, in run
    raise CekitError(
cekit.errors.CekitError: Test execution failed, please consult output above

Failing scenarios:
  features/image/jobs-service/kogito-jobs-service-ephemeral.feature:16  Verify if the debug is correctly enabled with the ephemeral jar
```

**Comment by ricardozanini** [comment]
This is the behave test:

```feature
  Scenario: Verify if the debug is correctly enabled with the ephemeral jar
    When container is started with env
      | variable     | value |
      | SCRIPT_DEBUG | true  |
    Then container log should contain -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/ephemeral/quarkus-app/quarkus-run.jar
    And container log should contain started in
    And container log should not contain Application failed to start
 ```

It's pretty simple and the application was just started since the first conditional passed.

**Comment by ricardozanini** [comment]
@jmtd @rnc which fork should I use now? I think we can merge the latest changes since it fixed the original bug. We can then dig into this new one in a separate issue? (Although I think they might be related)

**Comment by jmtd** [comment]
Hi @ricardozanini , the propose fix is already merged (https://github.com/cekit/behave-test-steps/pull/60), so you can use the normal repository `cekit/behave-test-steps`, or just don't specify `--steps-url` and let cekit default to that. I'm closing this because I _think_ you're saying this fix resolved the issue for you, but please re-open if I misunderstand.

**Comment by ricardozanini** [comment]
Thank you @jmtd!
