### ISSUE TITLE
Builds with docker fail with: "NameError: name 'docker' is not defined"

### ISSUE THREAD

**Issue by IoanDamianTR** [cekit/cekit#904]
**Describe the bug**
When running cekit with a docker build backend I encounter the following error:
NameError: name 'docker' is not defined`. Seem to be related to missing environment variables.

**To reproduce**
Amazon Linux 2 (Karroo) EC2 instance with docker-20.10.25-1.amzn2.0.4.x86_64 installed. CEKit v4.11.0.

Run cekit --descriptor <some_descriptor> build docker

**Expected behavior**
Should build image. Same files on a MacOS with cekit 4.11.0 and Docker Desktop pass.

**Environment information:**
 - Operating system: Amazon Linux 2
 - CEKit version: 4.11.0

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.
```024-03-26 09:54:02,414 docker.py:31         INFO  Handling artifacts for docker...
2024-03-26 09:54:02,414 docker.py:38         DEBUG Artifacts handled
2024-03-26 09:54:02,418 base.py:372        INFO  Rendering Dockerfile...
2024-03-26 09:54:02,491 base.py:391        DEBUG Dockerfile rendered
2024-03-26 09:54:02,491 builder.py:122        DEBUG Checking CEKit build dependencies...
2024-03-26 09:54:02,491 tools.py:509        DEBUG Checking if 'python-docker' dependency is provided...
2024-03-26 09:54:02,491 tools.py:515        DEBUG Required CEKit library 'python-docker' was found as a 'docker' module!
2024-03-26 09:54:02,491 tools.py:509        DEBUG Checking if 'docker-squash' dependency is provided...
2024-03-26 09:54:02,491 tools.py:515        DEBUG Required CEKit library 'docker-squash' was found as a 'docker_squash' module!
2024-03-26 09:54:02,491 tools.py:542        DEBUG All dependencies provided!
2024-03-26 09:54:02,492 docker_builder.py:257        DEBUG Building image with tags: 'amazon-buildbox:awscli', 'amazon-buildbox:latest'
2024-03-26 09:54:02,492 docker_builder.py:258        INFO  Building container image...
2024-03-26 09:54:02,492 docker_builder.py:184        DEBUG Preparing Docker client...
Traceback (most recent call last):
  File "/usr/local/bin/cekit", line 33, in <module>
    sys.exit(load_entry_point('cekit==4.11.0', 'console_scripts', 'cekit')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cekit/cli.py", line 192, in build_docker
    run_build(ctx, "docker")
  File "/usr/local/lib/python3.7/site-packages/cekit/cli.py", line 462, in run_build
    run_command(ctx, builder_impl)
  File "/usr/local/lib/python3.7/site-packages/cekit/cli.py", line 426, in run_command
    Cekit(params).run(clazz)
  File "/usr/local/lib/python3.7/site-packages/cekit/cli.py", line 528, in run
    command.execute()
  File "/usr/local/lib/python3.7/site-packages/cekit/builder.py", line 78, in execute
    self.run()
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 260, in run
    docker_client = self._docker_client()
  File "/usr/local/lib/python3.7/site-packages/cekit/builders/docker_builder.py", line 206, in _docker_client
    params.update(docker.utils.kwargs_from_env())
NameError: name 'docker' is not defined ```

**Comment by rnc** [comment]
Well this is strange. Did it work on prior versions? What is the output of `pip list installed` ?

**Comment by IoanDamianTR** [comment]
The system has both python 2.7 and python 3.7 installed. Amazon Linux 2 comes with python 2 by default. However all packages for cekit are installed for python 3.
```
 pip3 list installed
Package            Version
------------------ -----------
annotated-types    0.5.0
aws-cfn-bootstrap  2.0
boto3              1.21.33
cekit              4.11.0
certifi            2024.2.2
charset-normalizer 3.3.2
click              8.1.7
colorlog           6.8.2
docker             6.1.3
docker-squash      1.2.0
docopt             0.6.2
docutils           0.14
idna               3.6
importlib-metadata 6.7.0
Jinja2             3.1.3
lockfile           0.11.0
MarkupSafe         2.1.5
packaging          24.0
pip                20.2.2
pydantic           2.5.3
pydantic-core      2.14.6
pykwalify          1.8.0
pystache           0.5.4
python-daemon      2.2.3
python-dateutil    2.9.0.post0
python-docker      0.2.0
PyYAML             6.0.1
requests           2.31.0
ruamel.yaml        0.18.6
ruamel.yaml.clib   0.2.8
setuptools         49.1.3
simplejson         3.2.0
six                1.16.0
typing-extensions  4.7.1
urllib3            2.0.7
websocket-client   1.6.1
zipp               3.15.0
```

**Comment by rnc** [comment]
In a fresh virtualenv I get a different list:
```
pip list installed
Package            Version
------------------ -----------
cekit              4.11.0
click              8.1.7
colorlog           6.8.2
docopt             0.6.2
importlib-metadata 6.7.0
Jinja2             3.1.3
MarkupSafe         2.1.5
packaging          24.0
pip                23.2.1
pykwalify          1.8.0
python-dateutil    2.9.0.post0
PyYAML             6.0.1
ruamel.yaml        0.18.6
ruamel.yaml.clib   0.2.8
setuptools         67.7.2
six                1.16.0
typing_extensions  4.7.1
wheel              0.40.0
zipp               3.15.0
```

Adding docker/docker-squash gets
```
Package            Version
------------------ -----------
cekit              4.11.0
certifi            2024.2.2
charset-normalizer 3.3.2
click              8.1.7
colorlog           6.8.2
docker             6.1.3
docker-squash      1.2.0
docopt             0.6.2
idna               3.6
importlib-metadata 6.7.0
Jinja2             3.1.3
MarkupSafe         2.1.5
packaging          24.0
pip                23.2.1
pykwalify          1.8.0
python-dateutil    2.9.0.post0
PyYAML             6.0.1
requests           2.31.0
ruamel.yaml        0.18.6
ruamel.yaml.clib   0.2.8
setuptools         67.7.2
six                1.16.0
typing_extensions  4.7.1
urllib3            2.0.7
websocket-client   1.6.1
wheel              0.40.0
zipp               3.15.0
```


Did this work in prior versions? 

Can you retry with a local virtualenv outside of Amazon and see what you get? 

The line its failing on is https://github.com/cekit/cekit/blob/7f3924ffd542f8afbdb90ab2f73ec3ed8fbf6f8c/cekit/builders/docker_builder.py#L206 i.e. its failed to find the docker library. I actually made some changes to how this worked in the devel branch removing support for the old docker-py library (  https://github.com/cekit/cekit/commit/e2b785e24dadd8ad6e2c769540050fb4b6dff8e5 ) but I wouldn't have thought that would help your issue. 

If you run 
```
python                                                                                                                                                                                                           foobar-U-WXb69C 9:21
Python 3.7.17 (default, Feb 28 2024, 00:00:00) 
[GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> print(docker.constants.__version__)
6.1.3
>>> print(docker.utils.kwargs_from_env())
{}
>>> 
```
what do you get?

**Comment by IoanDamianTR** [comment]
Hmm... I think I found the issue thanks to your hint.
```
 python3
Python 3.7.16 (default, Aug 30 2023, 20:37:53)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/local/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.7/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
```

**Comment by rnc** [comment]
Excellent, looks like we found the problem! I have `openssl1.1-1.1.1q-5.fc39.x86_64` locally. I see references online e.g.
* https://github.com/urllib3/urllib3/issues/3016
* https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html

which should resolve it for you.

**Comment by rnc** [comment]
@IoanDamianTR While I think we have found the problem there are arguments for reexamining the CEKit loading / checking of modules. It currently masks the import error as optional library handling is done in https://github.com/cekit/cekit/blob/develop/cekit/tools.py#L459 and specifically for the libraries in https://github.com/cekit/cekit/blob/develop/cekit/tools.py#L548 
We could try an actual programmatic import (re https://docs.python.org/3/library/importlib.html#importing-programmatically ) which might help reveal this issue.
